### ISSUE TITLE
SelectionView Radio button Give Null in SelectedItems for the first time if not clicked on it 

### ISSUE THREAD

**Issue by prasad2694** [enisn/Xamarin.Forms.InputKit#100]
![image](https://user-images.githubusercontent.com/47597815/54804894-2a9bb480-4c9b-11e9-8e94-f98408ec0ae4.png)

can u help me how can i deselect all the radio button from start.
i am facing an issue until a user does not select or click any radio button i get null in selecteditems,
so i want for the first time none of the radio button is selected 

i am using SelectionView 

i also tried with selected index but index is not working correctly as for the first time index is always 1 for the radio button 1 but it should be 0 but on clicking on 2nd radio button the index is 1 and again if i click on radio button 1 the index is 0 now

**Comment by enisn** [comment]
It looks like an initialization problem of SelectionView.
I'm adding this bug to TODO list.

**Comment by enisn** [comment]
@prasad2694 
Can you try new version [v3.0.3](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.3)

That problem should be fixed at <a href="https://www.nuget.org/packages/Xamarin.Forms.InputKit/"><img src="https://img.shields.io/badge/Nuget-3.0.3-blue.svg" /></a>

**Comment by enisn** [comment]
I've just tried, I got the result. If it doesn't work at your project, re-open this issue. 👍
