### ISSUE TITLE
Hiding ValidationMessage until Validation issue

### ISSUE THREAD

**Issue by hjavaher** [enisn/Xamarin.Forms.InputKit#101]
**Is your feature request related to a problem? Please describe.**
ValidationMessage should be hidden until there is an error (usually after a button clicked or focus/unfocus

**Describe the solution you'd like**
It would be nice to configure validationmessage to be always visible or hidden until action (focus/unfocus or a button click)

**Comment by enisn** [comment]
I handled that problem like that:

If I don't bind the Text of AdvancedEntry, validation message is hidden until I sterted to type. 
But in new version, it'll be visible after Binding Text property.

**Comment by hjavaher** [comment]
Hi @enisn 
thanks for your reponse, this is my first app and I didn't know how to do data binding. These AdvancedEntry controls are just pointed to using their name in the view's code behind.

**Comment by enisn** [comment]
@hjavaher 
Can you try new version as <a href="https://www.nuget.org/packages/Xamarin.Forms.InputKit/"><img src="https://img.shields.io/badge/Nuget-3.0.3-blue.svg" /></a>

That problem should be fixed at [v3.0.3](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.3)

**Comment by hjavaher** [comment]
Hey, Just validated it. Thanks for the quick update!!!
