### ISSUE TITLE
Object reference not set to an instance of an object error

### ISSUE THREAD

**Issue by kevinvella** [enisn/Xamarin.Forms.InputKit#102]
**Describe the bug**
When i remove the Xamarin.Forms.InputKit package the application works.

**To Reproduce**
Trying to reproduce it in a sample app

**Expected behavior**
Does not crash

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 12.1
 - Version 12.1

Xamarin Forms v3.6.0.264807
Xamarin.Forms.InputKit v3.0.2
Xamarin Forms Material v3.6.0.264807

**Additional context**
`"  at Xamarin.Forms.VisualStateManager.GoToState (Xamarin.Forms.VisualElement visualElement, System.String name) [0x00000] in D:\\a\\1\\s\\Xamarin.Forms.Core\\VisualStateManager.cs:51 \n  at Plugin.InputKit.Platforms.iOS.StackLayoutWithVisualStatesRenderer.TouchesCancelled (Foundation.NSSet touches, UIKit.UIEvent evt) [0x00006] in <3af430ba27d545b5bdad56c17d32cb4e>:0 \n  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\n  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.16/src/Xamarin.iOS/UIKit/UIApplication.cs:79 \n  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.16/src/Xamarin.iOS/UIKit/UIApplication.cs:63 \n  at Nutrivitas.Mobile.iOS.Application.Main (System.String[] args) [0x00001] in `

I know this issue is a little vague. But i am trying to understand how this is being triggered myself.

**Comment by enisn** [comment]
Do you have a CustomRenderer which exported to `StackLayout` in your iOS project ?

**Comment by kevinvella** [comment]
I have custom renderers for pickers, and buttons.
And have a custom date picker based on grid and stack layout

I was not able to replicate it in a sample using the custom date picker only.
[InputKitException.zip](https://github.com/enisn/Xamarin.Forms.InputKit/files/2999517/InputKitException.zip)

**Comment by kevinvella** [comment]
Hi,
When will the update be available to nuget?

**Comment by enisn** [comment]
@kevinvella 

@prasad2694 
Can you try new version [v3.0.3](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.3)

That problem should be fixed at <a href="https://www.nuget.org/packages/Xamarin.Forms.InputKit/"><img src="https://img.shields.io/badge/Nuget-3.0.3-blue.svg" /></a>

**Comment by kevinvella** [comment]
@enisn 

Thanks. Confirming that the issue is fixed with this update.
Closing this issue. Thanks very much :)
