### ISSUE TITLE
Setting RadioButton.IsChecked = true does not update the ViewModel if the group is bound.

### ISSUE THREAD

**Issue by vchelaru** [enisn/Xamarin.Forms.InputKit#105]
**Describe the bug**
If a RadioButtonGroupView has its SelectedItemProperty bound to a property on a view model, manually clicking on any contained RadioButtons will update the view model, but setting a RadioButton's IsChecked property to true in code will not update the view model. 

It should, so that any approach of checking the RadioButton (either in code or manually by tapping on it) both update the view model.

**To Reproduce**

The following is a code snippet which will help explain the problem, but a full solution will require a little bit more work (specifically defining the view model and creating a page that contains the controls:

```
// Enum values used for the radio buttons:
public enum Values
{
    First,
    Second
}
public class MyViewModel
{
    public Values Value
    {
        // pseudocode to simplify the creation of the view model:
        get => GetValue();
        set => SetAndBroadcast(value);
    }
}

// inside your page:
public void PageType : ContentPage
{
    public PageType()
    {
        var stackLayout = new StackLayout();
        this.Content = stackLayout;
    
        this.BindingContext = new MyViewModel();

        var group = new RadioButtonGroupView();
        group.SetBinding(RadioButtonGroupView.SelectedItemProperty, nameof(MyViewModel.Value), BindingMode.TwoWay);
        stackLayout.Children.Add(group);

        var firstRadio = new RadioButton();
        firstRadio.Text = "First";
        firstRadio.Value = Values.First;
        group.Children.Add(firstRadio);

        var secondRadio = new RadioButton();
        secondRadio.Text = "second";
        secondRadio.Value = Values.Second;
        group.Children.Add(secondRadio);

        // Use the label to show the change in the property:
        var label = new StyledLabel();
        label.SetBinding(StyledLabel.TextProperty, nameof(MyViewModel.Value));
        stackLayout.Children.Add(label);

        // Default the second radio to checked
        secondRadio.IsChecked = true;
    }
}
```

**Expected behavior**
In this case the `secondRadio.IsChecked = true;` code should result in the group's SelectedItemProperty being updated, which will push the value to the view model. This should trigger a breakpoint on the ViewModel's setter, and should also update the label (assuming the view model properly broadcasts its change).

What actually happens is the label continues to say "First" instead of "Second". Note that manually clicking on the radio buttons does result in the label updating in real-time.

**Screenshots**

**Desktop (please complete the following information):**
Not tested on desktop versions.

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: 8.0 (Oreo)
 - No browser

**Additional context**
This behavior is very important to our project because we sometimes set defaults for radio buttons in our automated tests. The fact this behavior is not present makes certain automated tests more difficult to write.

Thanks so much for this awesome project!

**Comment by enisn** [comment]
@vchelaru 
Good Catch!
Setting directly property, passes bindable property and affect directly to design.
I'll make that process able to work with bindable property.

**Comment by enisn** [comment]
https://github.com/enisn/Xamarin.Forms.InputKit/blob/c1f8d4b01a82309780302edd31d848b596c5c0c4/InputKit/Shared/Controls/RadioButtonGroupView.cs#L173

It sends the value in that version. I think problem occours with boxed values. Type of `Value` property is  Object  as **ReferenceType** and you set into it an Enum as **ValueType**, 
Can you try change Property Type to Object in your ViewModel ?
* * *
I'm still working on it. 👍

**Comment by vchelaru** [comment]
Yes, as you guessed, if I use a reference type instead of an enum then everything works great. Unfortunately  I use enums throughout my app and the RadioButton control is usually the UI element that I use when I have to represent enum data to the user, so I won't be able to use that as a workaround in my app.

**Comment by vchelaru** [comment]
So I looked into the code and I actually don't believe it has to do with enums/boxed values. The reason is I'm looking at the code in RadioButtonGroupView:

```
private void OnChildAdded(object sender, ElementEventArgs e)
{
    if (e.Element is RadioButton rb)
    {
        rb.Clicked -= UpdateSelected;
        rb.Clicked += UpdateSelected;
    }
    ....
```

That seems to only react to clicks, as opposed to the `IsChecked` property changing.

I think the solution is to have a separate event on when the checked changes, since clicking is not the same thing as changing the checked value.

What do you think about adding a Checked event? I can add it in a PR.

**Comment by vchelaru** [comment]
Fixed with my PR linked above
