### ISSUE TITLE
RadioButtons seem to lose their Text when clicked 

### ISSUE THREAD

**Issue by vchelaru** [enisn/Xamarin.Forms.InputKit#106]
**Describe the bug**
RadioButtons initially display their Text, but the text disappears when clicked. This was not a problem in previous versions (I was previously using 2.3.6), but after upgrading to 3.0.4 this seems to be happening, so it maybe was introduced recently.

**To Reproduce**

The following code reproduced the problem for me:

```
var stackLayout = new StackLayout();
this.Content = stackLayout;

var group = new RadioButtonGroupView();
stackLayout.Children.Add(group);

var firstRadio = new RadioButton();
firstRadio.Text = "First";
group.Children.Add(firstRadio);

var secondRadio = new RadioButton();
secondRadio.Text = "Second";
group.Children.Add(secondRadio);
```

**Expected behavior**
The radio buttons should continue to display "First" and "Second" after being clicked.

**Screenshots**
![2019-03-27_14-19-13](https://user-images.githubusercontent.com/729631/55109482-93b86900-509b-11e9-84b5-5021d65aa594.gif)

**Desktop (please complete the following information):**
Not tested on desktop.

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: 8.0 (Oreo)
 - Version: InputKit version 3.0.4

**Additional context**
As mentioned above, I think this might be a new bug caused some point between 2.3.6 and 3.0.4, but I haven't upgraded frequently enough to know exactly where.

Thanks so much for this great library!

**Comment by enisn** [comment]
https://github.com/enisn/Xamarin.Forms.InputKit/blob/master/InputKit/Shared/Controls/RadioButton.cs#L253

As I see, default value of TextColor returns Transparent. I'm working on it 👍.

Until I update, can you try set a TextColor like Black or something else?

**Comment by vchelaru** [comment]
I will do that. Thanks so much for the rapid response and awesome project!

**Comment by enisn** [comment]
Can you give me more specified information about that. I couldn't handle that problem when I tried same code with you.

Can something affects from **Resources/values/styles.xml** in your Android project? 
Like text color or something else?

**Comment by vchelaru** [comment]
If I explicitly set the TextColor to Black then all works okay:

```
var firstRadio = new RadioButton();
firstRadio.TextColor = Color.Black; // <- This fixes it...
firstRadio.Text = "First";
firstRadio.Value = Values.First;
group.Children.Add(firstRadio);


var secondRadio = new RadioButton();
secondRadio.TextColor = Color.Black; // <- And this also fixes it...
secondRadio.Text = "second";
secondRadio.Value = Values.Second;
group.Children.Add(secondRadio);
```

I don't know enough about how styles.xml works to know if something is overridden there. But I don't think there's anything there that could impact this:

```
<resources>

    <!--
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    -->
    <style name="AppBaseTheme" parent="Theme.AppCompat">
        <!--
            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        -->
    </style>

    <!-- Application theme. -->
    <style name="AppTheme" parent="AppBaseTheme">
        <!-- All customizations that are NOT specific to a particular API-level can go here. -->
      <item name="android:windowNoTitle">false</item>
    </style>

    <style name="SplashTheme" parent="Theme.AppCompat.NoActionBar">
        <item name="android:windowBackground">@drawable/background_splash</item>
    </style>

</resources>
```

Anyway, the workaround of setting the text color is good enough for me because I plan on doing that anyway. Not sure if it's worth keeping this open at this point or not if it doesn't reproduce for you.

**Comment by vchelaru** [comment]
If it helps any, I found that even if I set the text color explicitly, it doesn't work if I use the RadioButton constructor that takes a string.

If I set the color *then* set the text, everything works okay...there's definitely something going on here but it's hard to track down exactly.

**Comment by enisn** [comment]
@vchelaru I still can not handle this issue. Can you make it in a new project and share source code ?

**Comment by enisn** [comment]
Problem occurred by constructor with text paramater. It's marked as obsolete.
