### ISSUE TITLE
Adding Image to Radio Button

### ISSUE THREAD

**Issue by prasad2694** [enisn/Xamarin.Forms.InputKit#107]
can i add a image to radio button of selecterview, i am trying to make a radio button for gender and i need to show image of male and female on radio button

**Comment by enisn** [comment]
It's not possible for now with **SelectionView**. Also customization requeset almost same with #94 

* * *
But you can generate two radiobutton manually with following XAML code:

```xml
<controls:RadioButtonGroupView SelectedIndex="{Binding SelectedGenderIndex}">
	<controls:RadioButton Text="Female" CheckedImage="your_female_image.png" />
	<controls:RadioButton Text="Male" CheckedImage="your_male_image.png"/>
</controls:RadioButtonGroupView>
```
