### ISSUE TITLE
MVVM

### ISSUE THREAD

**Issue by Chuckle999** [enisn/Xamarin.Forms.InputKit#11]
I've tried using this with MVVM, using EventToCommand functionality but... to no avail.  How?

**Comment by enisn** [comment]
I couldn't understand the question,

For example you have a checkbox and you need to handle when user tap on it and changed check situation.

XAML

```xml

<input:CheckBox Text="Sample Option" IsChecked="{Binding OptionCheckhed}" />
```


CS:
```csharp
  public bool OptionChecked { get => _optionChecked; 
set 
 { 
  _optionChecked = value;
   OnPropertyChanged();  
  //YOU CAN HANDLE HERE WHEN CHECK CHANGED
  }
 }
```

**Comment by Chuckle999** [comment]
Thanks for the response.

So I'm trying to implement the control in an MVVM based app in the ViewModel, the example you show is in the CodeBehind.

**Comment by Chuckle999** [comment]
I probably haven't explained what I'm trying to do properly - what I'm really looking for is a way to catch when the control is toggled either on or off.

**Comment by enisn** [comment]
Just bind your property to control's bindableproperty, it'll trigger **SET** method of property with value. You can handle changes in set methods of your properties. If you can share your code I can help you easier

**Comment by Chuckle999** [comment]
Would just like to mention that my question was not specific enough, and that **I have managed to resolve**: the problem I was having was binding the CheckBox command inside a ListView.  Thankyou for your help!
