### ISSUE TITLE
Checkbox text on the left instead of the right?

### ISSUE THREAD

**Issue by J3nova1628** [enisn/Xamarin.Forms.InputKit#112]
Is it possible to have the text on the left of the checkbox instead of the right ?

**Comment by enisn** [comment]
@J3nova1628 There is awaiting a Pull Request about that #111 

Until merge will be completed. You can try to set `FlowDirection` as `RightToLeft` to to that easily.

```xml
<input:CheckBox Text="This sample text" FlowDirection="RightToLeft" />
```

**Comment by J3nova1628** [comment]
@enisn I have tried this but nothing is happening

**Comment by J3nova1628** [comment]
@enisn Apologises it worked after i rebuilt the solutions

**Comment by enisn** [comment]
@J3nova1628  
It's possible not in [v3.0.6](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.6) and later versions.
Just set `LabelPosition` property of CheckBox and magic happens.

```xml
<input:CheckBox Text="Sample Text" LabelPosition="After" />
```
