### ISSUE TITLE
Dropdown view is too big on IOS

### ISSUE THREAD

**Issue by huxaiphaer** [enisn/Xamarin.Forms.InputKit#114]
**Describe the bug**
Dropdown size is too big on IOS

**To Reproduce**
1. After installing the Nuget package in the IOS project.
2. Then run the application on the simulator.

**Expected behavior**
The dropdown should be of the same size with the one on Android

**Screenshots**
<img width="354" alt="Screen Shot 2019-04-04 at 22 53 18" src="https://user-images.githubusercontent.com/14312249/55584256-7f740c00-572c-11e9-8b88-6d9e905b389a.png">

**Comment by minhtk1** [comment]
@enisn fix bug?

**Comment by AhmedAdelGadElkareeem** [comment]
@enisn this bug not fixed yet :( :(

**Comment by nouraal** [comment]
**Hello**

Thankful and appreciated your hard work.


**To Reproduce:**
- For Dropdown size it's has been fixed for phone screen but not for **big-screen** like tablet the issue still there.



**Screenshots:**

![inptKitError](https://user-images.githubusercontent.com/14325480/105696454-69909600-5f14-11eb-8a06-6944b9a5cfc8.png)
