### ISSUE TITLE
CheckChangedCommand event is not called in a BindableLayout, for dynamically created checkboxes. Xamarim Forms 3.6.0.293080.

### ISSUE THREAD

**Issue by araujoCRS** [enisn/Xamarin.Forms.InputKit#115]
**Describe the bug**
CheckChangedCommand event is not called in a BindableLayout, for dynamically created checkboxes. Xamarim Forms 3.6.0.293080.

**To Reproduce**

```xml
<StackLayout BindableLayout.ItemsSource='{Binding Answers}' Spacing='0' Margin='0' Padding='0'>
    <BindableLayout.ItemTemplate>
        <DataTemplate>
            <input:CheckBox x:Name='Teste' Text='{Binding Description}' Type='Box' CheckChangedCommand='{Binding CheckChangedCommand}' CommandParameter='{Binding Id}'/>
        </DataTemplate>
    </BindableLayout.ItemTemplate>
</StackLayout>
```

**Expected behavior**
Call function:

```csharp
CheckChangedCommand = new Command(CheckChanged);
private void CheckChanged(object answer)
        {
            var resp = _respostas.First(x => x.Id == answer);
            App.Current.MainPage.DisplayAlert("Resposta", resp.Description,"OK");
        }
```

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI 8 lite
 - OS: Android 9
 - Version MIUI Global 10.2

**Additional context**
Create a dynamic checkbox list linked to the View Model. Following the MVVM standard.

**Comment by ScarlettCode** [comment]
Any progress on this issue?

**Comment by enisn** [comment]
I can't understand the issue, but
You can use [SelectionView](https://enisn-projects.io/docs/en/inputkit/latest/components/controls/SelectionView) to achieve the same goal with less pain

**Comment by araujoCRS** [comment]
I abandoned all projects in Xamarin and the technology. I can't help with this issue anymore. Sorry.
