### ISSUE TITLE
Radio Button in IOS are rendering Big

### ISSUE THREAD

**Issue by ronakshethia** [enisn/Xamarin.Forms.InputKit#117]
i have provided same height and weight for selector view still in IOS radio button are displayed in bigger size

![image](https://user-images.githubusercontent.com/35444818/55796201-00ddec80-5ae7-11e9-90c7-20031ed25645.png)

**Comment by enisn** [comment]
It looks it was happened at last release.
 I'm working on it

**Comment by vchelaru** [comment]
I've also hit this :( Any updates on a fix, as we're close to releasing a version of our app that has this problem on iOS.

**Comment by enisn** [comment]
I think this issue happend after merged pull request  #108 .
Nowadays I'm little busy. I'm Sorry about that much time waiting. 
I'm working on it.

**Comment by enisn** [comment]
@ronakshethia  @vchelaru 
As I can see, you can set `CircleSize` property and you can change your own CircleSize as  you wish until Fix will be released.

**Comment by enisn** [comment]
I've found!
The problem occured from default value of CircleSizeProperty
https://github.com/enisn/Xamarin.Forms.InputKit/pull/108/commits/37407d29262df78526964c60fa50a1bc136d21a6#diff-3017d6ccc803e43084d76bfa83b1ec7aR219

**Comment by enisn** [comment]
Can you check [v3.0.8](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v3.0.8),? Default value of CircleSize is `-1` now.

**Comment by enisn** [comment]
If issue occurs again just re-open it. I think it was solved.
