### ISSUE TITLE
Background Color of checkbox not using BoxBackgroundColor

### ISSUE THREAD

**Issue by Giorgi** [enisn/Xamarin.Forms.InputKit#119]
**Describe the bug**
Background color of the checkbox uses BackgroundColor property instead of BoxBackgroundColor

**To Reproduce**
1. Set BoxBackgroundColor to some color, for example Red
2. The background color is not red

**Expected behavior**
The background of checkbox should be red

**Smartphone (please complete the following information):**
 - Version 3.0.7

**Additional context**
In `UpdateColors` it should be using BoxBackgroundColor instead of BackgroundColor property

**Comment by enisn** [comment]
@Giorgi  Yeah, You're right. A mistake was happened while updating v3. 
I'm working on it

**Comment by enisn** [comment]
@Giorgi 
Can you check [v3.0.8](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v3.0.8)
