### ISSUE TITLE
Value each time I slide 

### ISSUE THREAD

**Issue by josebarrontovar** [enisn/Xamarin.Forms.InputKit#12]
How do I get the value each time I slide the slider?
  

Value = "{Binding Path = Status, Mode = TwoWay}" // XAML

  public double Status {get; set; }
         public MainPage ()
{// CODEBH
             var x = this.Status;
}

Greetings.

**Comment by enisn** [comment]
I'm working on it, I'll update soon as possible

**Comment by enisn** [comment]
I've tested on 1.1.0 version and it triggers set method. 
Do you need continuously sets instead of last value set ?

**Comment by josebarrontovar** [comment]
Yes, when i move the slider, i want to know exactly value of slider :)

**Comment by enisn** [comment]
That bug was fixed. 
Tested on **v.1.2.0** and it works fine now.
You can find newest version from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit)
