### ISSUE TITLE
Xfx.Controls can't be used along Xamarin.Forms.InputKit

### ISSUE THREAD

**Issue by Juansero29** [enisn/Xamarin.Forms.InputKit#120]
**Describe the bug**
When using the NuGet package Xamarin.Forms.InputKit (v3.0.7) and Xfx.Controls(v1.2.1) and trying to deploy an app, I get an error from registration of native controls since they have the same name. I have checked in both NuGets and they do have the same name, but not only that, they have the same code!

XfX: 
![image](https://user-images.githubusercontent.com/19156405/56216871-84a55500-6062-11e9-81fb-1d16858d05ef.png)

InputKit:

![image](https://user-images.githubusercontent.com/19156405/56216922-9ab31580-6062-11e9-9d5a-01760aa45c9c.png)

Hence, it causes the following error when deploying the project for iOS :

Error

Could not register the assembly 'Xfx.Controls.iOS': error MT4118: Cannot register two managed types ('MBAutoComplete.MbAutoCompleteTextField, Xfx.Controls.iOS' and 'Plugin.InputKit.Platforms.iOS.Controls.AutoCompleteTextField, Plugin.InputKit') with the same native name ('MbAutoCompleteTextField').

This shouldn't be happening. I post the issue here because the Xfx control is there since July 2018 whereas the InputKit control is there since March 2019. Which means @enisn has taken the control and just copied it into InputKit. I don't know if you have the right to that, but anyways, I think you should either remove this control from your NuGet package or change the name of the Register line so that the two NuGet packages can coexist together in the same project.

**To Reproduce**
1. Create a new solution, Xamarin.Forms.InputKit (v3.0.7) and Xfx.Controls(v1.2.1)
2. Deploy the solution on iOS
3. See error

**Expected behavior**
The project should build and deploy without any problems

**Additional context**
My app uses the SelectionView from InputKit, but also uses entries and other controls from Xfx.Controls, so I need both NuGets to be present in my project.

**Comment by enisn** [comment]
[MBAutoComplete](https://github.com/MarcBruins/MBAutoComplete) is common control for ios. Register name can be changed for prevent conflicts as soon as possible

**Comment by enisn** [comment]
Can you try build with new version [v3.0.8](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v3.0.8) ?

**Comment by Juansero29** [comment]
I will try that tomorrow!  I'll keep you updated

**Comment by Juansero29** [comment]
I haven't have got the time yet to test this out, but it should probably work! I think it is safe to close the bug,
