### ISSUE TITLE
Can't use this package.

### ISSUE THREAD

**Issue by blockfan7** [enisn/Xamarin.Forms.InputKit#123]
I installed Xamarin.Forms.InputKit 3.0.7. And it was working well.
Today, I updated it to 3.0.8.1.
Suddenly following error occurred
![error](https://user-images.githubusercontent.com/41097491/56437541-171b5200-630a-11e9-9e62-9b8a95c7b54d.png)
.

**> #CS0234 The type or namespace name 'Platforms' does not exist in the namespace 'Plugin.InputKit' (are you missing an assembly reference?)**

As I said, there's no error when I was using 3.0.7. 
I am using Xamarin.Forms 3.6.0.264807

I am confused. Please help me

**Comment by enisn** [comment]
After v3.0.8 ,
InputKit Mono Android target changed to 9.0.

Can you try to set your Android project's Target Framework as Android 9.0?

**Comment by blockfan7** [comment]
Thank you.I changed the Android Framework and it's working.

**Comment by tjdennis** [comment]
I'm having the same problem. Unfortunately, VS2019 doesn't provide an Android 9 choice to target to.  I found the API 28 SDK in the sdk manager, but there are no API 28 build tools there to install.  I see them in the unsupported google repository, but until Microsoft adds them to its own android sdk repository, I'm not sure this package can be used anymore from VS until they update.

**Comment by enisn** [comment]
Both of Mono Android 90 and Mono Android 81 were targetted at [v3.0.10](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v3.0.10)

**Comment by enisn** [comment]
On latest version, both monoandroid9.0 and monoandroid10.0 is supported. 

I think this issue it outdated now.

---
Feel free to re-open this issue if problem continues.
