### ISSUE TITLE
Checkbox IsChecked Two Way Binding not working

### ISSUE THREAD

**Issue by keithabramo** [enisn/Xamarin.Forms.InputKit#125]
**Describe the bug**
When setting the IsChecked property to something like` IsChecked="{Binding IsSelected, Mode=TwoWay}"` then updating the IsSelected property in the viewmodel, the checkbox is not changing to checked/unchecked accordingly.

**To Reproduce**
1. Bind a property to the IsChecked attribute of the Checkbox
2. Change that property in the viewmodel via codebehind code
3. Observe the checkbox does not change automatically in the UI

**Expected behavior**
When a property bound to the IsChecked attribute on the Checkbox is changed, Two way binding should automatically change the checkbox UI to be checked/unchecked

**Smartphone (please complete the following information):**
 - OS: Android and ios

**Comment by enisn** [comment]
@keithabramo 
Can you share a part of your code?
I couldn't handle same problem

**Comment by elsi13** [comment]
I Have the same problem.

`<input:CheckBox Text="{Binding Name}" Type="Check" CheckChangedCommand="{Binding Source={x:Reference VanInventory}, Path=BindingContext.ToggleCommand }"  CommandParameter="{Binding .}"
 IsChecked="{Binding Checked}" StyleClass="VanLabel"/>`

where Checked is my boolean value; and I have function for the command to toggle the boolean:

`        public async void ToggleCommandHandle(VanInventory van)
        {
            van.Checked = !van.Checked;
            await App.SiteVisitsDB.UpdateItem<VanInventory>(van);
        }`

**Comment by acaliaro** [comment]
In XF4.1 should exist the "official" checkbox

**Comment by enisn** [comment]
Sorry for late reply, 
I've just checked, It's working two way. If issue continues still please describe more, how is your viewmodel ?

**Comment by enisn** [comment]
Checked again, Two-way binding works fine . If problem occurs again, please re-open this issue with more details.

**Comment by lccarvalho** [comment]
When inside a ListView the two way really doesn't seem to work, please see my code below:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="TesteBinding.MainPage">

    <StackLayout Margin="20,35,20,20">
        <ListView x:Name="turmasListView" ItemsSource="{Binding Alunos}">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition/>
                                <ColumnDefinition/>
                            </Grid.ColumnDefinitions>
                            <Label 
                                   Text="{Binding Nome}"
                                   HorizontalOptions="Start"/>
                            <CheckBox Grid.Column="1"
                                   IsChecked="{Binding Presente, Mode=TwoWay}"                                   
                                   HorizontalOptions="End"/>
                        </Grid>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
        <Grid VerticalOptions="End">
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
            </Grid.RowDefinitions>
            <Button x:Name="TogglePresenças" Text="VVVV"
                Clicked="OnTogglePresençasButtonClicked"
                HorizontalOptions="Start"/>
        </Grid>
    </StackLayout>
</ContentPage>

```

`using System;
using System.Collections.Generic;
using Xamarin.Forms;

namespace TesteBinding
{
    public partial class MainPage : ContentPage
    {
        public IList<Aluno> Alunos { get; set; }
        public MainPage()
        {
            InitializeComponent();
            Alunos = new List<Aluno>()
            {
                new Aluno { Nome="Fulano", Presente=false },
                new Aluno { Nome="Beltrano", Presente=false },
                new Aluno { Nome="Sicrano", Presente=false }
            };
            BindingContext = this;
        }

        protected void OnTogglePresençasButtonClicked(object sender, EventArgs e)
        {
            foreach(var a in Alunos)
            {
                a.Presente = true;
            }
        }



    }
    public class Aluno
    {
        public string Nome { get; set; }
        public bool Presente { get; set; }

    }
}
`

**Comment by lccarvalho** [comment]
Sorry, not using Input Kit, should report this elsewhere
