### ISSUE TITLE
No property, bindable property, or event found for 'ClickCommand', or mismatching type between value and property.

### ISSUE THREAD

**Issue by TizioFittizio** [enisn/Xamarin.Forms.InputKit#13]
I got an error while trying to bind a command in a radio button:

> No property, bindable property, or event found for 'ClickCommand', or mismatching type between value and property.

This is my code:

I import the plugin:
`xmlns:controls="clr-namespace:Plugin.InputKit.Shared.Controls;assembly=Plugin.InputKit"`

I wire my viewmodel:
`BindingContext="{Binding FiltersViewModel, Source={StaticResource Locator}}`

This is the element which i am trying to add the command:
```
<controls:RadioButton 
                        Text="1"  
                        Value="{Binding DataAggregation1}" 
                        ClickCommand="{Binding ChangeDataAggregationCommand}"/>
```

The line where the error occours:
`ClickCommand="{Binding ChangeDataAggregationCommand}"/>`

The command is an ICommand in my ViewModel:
`public ICommand ChangeDataAggregationCommand { get; set; }`

The others bindings works fine

**Comment by Trostan** [comment]
I got exactly the same Problem.

**Comment by enisn** [comment]
There is a missing BindableProperty for ClickCommand. There was a mistake. I've just solved it and updated NuGet Package. 

It's available above v.1.1.1 on Nuget from <a href="https://www.nuget.org/packages/Xamarin.Forms.InputKit/1.1.1">here</a>
