### ISSUE TITLE
Focused eventhandler not being thrown - advancedentry

### ISSUE THREAD

**Issue by LeoJHarris** [enisn/Xamarin.Forms.InputKit#130]
Hi @enmisn I am using your advanced entry and I am having trouble raising the Focused EventHandler. Subscribing to the Focused event and tapping into the advanced entry is not raising the subscribed event

**Comment by enisn** [comment]
It seems a bug, I need to investigate it.

**Comment by enisn** [comment]
Can you check [v3.0.15](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v3.0.15) Update?
If problem still coninutes feel free to re-open this issue.
