### ISSUE TITLE
FontFamily property for Checkbox is not Bindable

### ISSUE THREAD

**Issue by Hakim83** [enisn/Xamarin.Forms.InputKit#134]
FontFamily property of Checkbox is not bindable,
It works well for Radio button however.
for example:
<controls:CheckBox FontFamily="{Binding myFontName}" ... /> fail to compile, however
<controls:CheckBox FontFamily="some-font-name" .../> works well

**Comment by LeoJHarris** [comment]
Same for Placeholder for AdvancedEntry...

**Comment by LeoJHarris** [comment]
error : Position 65:25. No property, bindable property, or event found for 'Placeholder', or mismatching type between value and property.

**Comment by LeoJHarris** [comment]
Also had the same issue on MaxValue on AdvancedSlider, this seems to apply to a couple of components where some properties are fine and others are not.

**Comment by enisn** [comment]
Duplicated by #204
