### ISSUE TITLE
System.InvalidCastException: Specified cast is not valid?

### ISSUE THREAD

**Issue by sagarmp02** [enisn/Xamarin.Forms.InputKit#136]
When I am binding checkbox dynamically it is giving me error like **"System.InvalidCastException: Specified cast is not valid."**

Following is what I am trying

`<StackLayout x:Name="roll"  HeightRequest="0">
                        <SearchBar Placeholder="Type to Search" TextChanged="SearchDropDown"></SearchBar>
                        <ListView  x:Name="SearchDropDownList" ItemsSource="{Binding Items}" CachingStrategy="RecycleElement" ItemSelected="OnItemSelected">
                            <ListView.ItemTemplate>
                                <DataTemplate>
                                    <input:CheckBox Text="{Binding Text}" />
                                </DataTemplate>
                            </ListView.ItemTemplate>
                        </ListView>
                    </StackLayout>`

**Comment by enisn** [comment]
Yeah that's the right answer @Khaon
