### ISSUE TITLE
HorizontalTextAlignment for AdvancedEntry

### ISSUE THREAD

**Issue by ahmedelsyaed** [enisn/Xamarin.Forms.InputKit#137]
using Xamarin.Forms.InputKit v 3.0.11
HorizontalTextAlignment property is not presented.

**Comment by kinglionsoft** [comment]
ReturnType property is not presented.

**Comment by enisn** [comment]
Check [v3.2.2](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.2.2)
