### ISSUE TITLE
RadioButtonGroupView IsChecked/Value Bindable Property not working

### ISSUE THREAD

**Issue by muhammetsahin** [enisn/Xamarin.Forms.InputKit#14]
I'm using version 1.1.1

Here is my XAML code 

      <input:RadioButtonGroupView SelectedItem="">
        <input:RadioButton
          IsChecked="{Binding RbCradle, Mode=TwoWay}"
          Text="Cradle"
          TextColor="Black" />
        <input:RadioButton
          IsChecked="{Binding RbWireless, Mode=TwoWay}"
          Text="Wireless"
          TextColor="Black" />
      </input:RadioButtonGroupView>

AND MVVM Backend (Prism.Forms)

  private bool _rbCradle;
    public bool RbCradle
    {
      get => _rbCradle;
      set => SetProperty(ref _rbCradle, value);
    }

    private bool _rbWireless;
    public bool RbWireless
    {
      get => _rbWireless;
      set => SetProperty(ref _rbWireless, value);
    }

But  value or is selected return always false.
![image](https://user-images.githubusercontent.com/2045788/42512855-49aa8d16-845e-11e8-8b0d-f4e1d9940ee1.png)
![image](https://user-images.githubusercontent.com/2045788/42512901-620653ea-845e-11e8-9b0e-b2cc64f4fffa.png)

**Comment by enisn** [comment]
I think there is a missing trigger inside RadioButton. Can you try to bind **RadioButtonGroupView**'s **SelectedIndex** property for now. I'l solve that problem soon as possible.

**Comment by enisn** [comment]
That bug was fixed with v.1.2.0. You can bind **IsChecked** property for **RadioButton** with **Mode=TwoWay** and it'll send the last state to your viewmodel.

You can find v.1.2.0 from <a href="https://www.nuget.org/packages/Xamarin.Forms.InputKit/1.2.0"> here</a>

**Comment by muhammetsahin** [comment]
Thank you for support. Problem solved.

Best Regards.
