### ISSUE TITLE
App is crashing when Advance Entry Field is Empty

### ISSUE THREAD

**Issue by eliyasbaby** [enisn/Xamarin.Forms.InputKit#144]
**Describe the bug**
`<input:AdvancedEntry 
                    x:Name="Goal" 
                    TextColor="Black"
                    Text="{Binding SelectedJob.Goal}"
                    IsRequired="True"
                    Annotation="DigitsOnly"
                    Title="Goal:"
                    Placeholder="Enter Goal"
                     BorderColor="#001f3f"
                    />`
I am binding one integer field to AdvancedEntry. So on page load it will show 0 in the input field.when i clear the field(keyboard back button) app is crashing.
**To Reproduce**
1-bind an integer field
2-try to clear the default 0
3-No Exception is getting
**Expected behavior**
User should able to type after removing that 0

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 4
 - OS: Android 9.0
 

**Additional context**

**Comment by enisn** [comment]
You're right. There is no null check to converting your binding type. 

It should return default of binded type while entry field is empty instead of null. 
I'm working on it.

**Comment by eliyasbaby** [comment]
@enisn can we expect this fix very soon?..This will be very helpful!...

**Comment by enisn** [comment]
https://github.com/enisn/Xamarin.Forms.InputKit/blob/21bee138fe750d2bbbd4d46376a04ad9f618bbd7/InputKit/Shared/Controls/AdvancedEntry.cs#L434
It just notifies with **SetValue()** method from BindableObject. There is not a harcoded convert or return here.
The AdvancedEntry doesn't know type of what you bind.

**Comment by SAISUDHEERREDDY** [comment]
@enisn  Hello Enisn ,
 I'm also facing same issue , any update on this  issue , if this issue will fix it will be very help full for me  .InputKit is  awesome Ui 
Thank you

**Comment by SAISUDHEERREDDY** [comment]
@eliyasbaby  did u find any solution on this issue

**Comment by enisn** [comment]
Bug couldn't be handled at `v3.1.0`.
Feel free to re-open this issue again if problem occurs again
