### ISSUE TITLE
Radio button inside a dialog kit popup and text box ?./

### ISSUE THREAD

**Issue by davidbuckleyni** [enisn/Xamarin.Forms.InputKit#145]
I love your popup and using it with input kit makes it so easy but I have a requirement where I required a radio button to let the user pick if it's a negative adjustment or a positive adjustment and then enter the qty in the text box is it possible to also have a radio button in the same popup

It's here I need a radio button as well if that is possible
var resultQty = await Plugin.DialogKit.CrossDiaglogKit.Current.GetInputTextAsync("Fuel", "Please enter the visible stock of the item.");

**Comment by enisn** [comment]
@davidbuckleyni 
DialogKit is too old package. It depends on Inputkit `v2.x.x`, 
Just try use it with InputKit `v2.3.8`, this will fix the problem. 

---

I can update DialogKit for InputKit `v3.x.x` later. But this is solution for now.
