### ISSUE TITLE
Constructor of the RadioButton not show the string value option.

### ISSUE THREAD

**Issue by aismaniotto** [enisn/Xamarin.Forms.InputKit#148]
**Describe the bug**
If the RadioButton is instantiated with parameters constructors (by code behind), the values will be setted, but the option will not show.

**To Reproduce**
1. Instantiat a RadioButton with some parameter by the code behind.
2. Add to Stacklayout or RadioButtonGroupView
3. Run the code
4. No options will be show, just the Radio icon

**Expected behavior**
Render the option on radio button.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android, iOS

**Smartphone (please complete the following information):**
 - Device: Moto G4
 - OS: Android 7.1

**Additional context**
If the input is instantiated with the empty constructor and after that put the values, will work perfectly (I guess that what is done when is instantiated on XAML)

**Comment by enisn** [comment]
I think this is related with #106

**Comment by enisn** [comment]
Which constructor are you using?

This one: 
https://github.com/enisn/Xamarin.Forms.InputKit/blob/master/InputKit/Shared/Controls/RadioButton.cs#L86-L96

or this one:
https://github.com/enisn/Xamarin.Forms.InputKit/blob/master/InputKit/Shared/Controls/RadioButton.cs#L103-L109
Last one is already marked as **obsolete** and it's not stable to use.

**Comment by aismaniotto** [comment]
Seems similar with this issue. I tested with both constructors and get the same result. The workaround I find is use the empty constructor and in sequence, attribute the properties.

**Comment by enisn** [comment]
@aismaniotto 
OK, I'm labeling it as bug, and add to bug solving queue.

Until the solution of problem can you use object initializer:

```csharp
var rb = new RadioButton 
{
	Text = "My option",
	Color = Color.Blue
	//...
}
```

**Comment by enisn** [comment]
These constructors are deprecated in [v3.0.15](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v3.0.15) ?
