### ISSUE TITLE
Add a label to RadioButtonGroupView

### ISSUE THREAD

**Issue by Marium-Hashmi** [enisn/Xamarin.Forms.InputKit#15]
How to add a label to RadioButtonGroupView?

<input:RadioButtonGroupView>
                   <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*"></ColumnDefinition>
                        <ColumnDefinition Width="*"></ColumnDefinition>
                    </Grid.ColumnDefinitions>
                    <input:RadioButton Text="Option 1" CircleColor="#55B778" Grid.Column="0" Grid.Row="0"/>
                        <Label Grid.Column="1" Grid.Row="0">Price</Label>
                    </Grid>
</input:RadioButtonGroupView>

I've tried adding radio buttons and labels to a grid and then adding the grid to RadioButtonGroupView, but it allows all the radio buttons to be checked in the group.

 Any suggestion would be appreciated.

**Comment by enisn** [comment]
If you need a grid with multiple columns you can use **SelectionView**


```xml
   <input:SelectionView x:Name="selectionView" ColumnNumber="3" SelectionType="RadioButton"/>
```

and you can set ItemsSource like:

```csharp
            selectionView.ItemsSource = new[]
            {
                new SampleClass{ Name = "Option 1", Id = 1 },
                new SampleClass{ Name = "Option 2", Id = 2 },
                new SampleClass{ Name = "Option 3", Id = 3 },
                new SampleClass{ Name = "Option 4", Id = 4 },
                new SampleClass{ Name = "Option 5", Id = 5 },
                new SampleClass{ Name = "Option 6", Id = 6 },
                new SampleClass{ Name = "Option 7", Id = 7 },
                new SampleClass{ Name = "Option 8", Id = 8 },
            };
```
It'll look like 3 column Radio Buttons or how many column you want.
You can reach selected item with **SelectecItem** property of SelectionView

**Comment by enisn** [comment]
@Marium-Hashmi
You can put any control inside of RadioButtonGroupView

```xml
            <input:RadioButtonGroupView>
                <Label Text="Choose one option" />
                <input:RadioButton Text="Option 1" />
                <input:RadioButton Text="Option 2" />
                <input:RadioButton Text="Option 3" />
                <input:RadioButton Text="Option 4" />
            </input:RadioButtonGroupView>
```

It'll recognize only radiobuttons. Other buttons won't be affected

**Comment by Marium-Hashmi** [comment]
Thank you for the response.
The first response would give me three columns of radio buttons (I want one column of radio button with labels in second column).
What I want is this:
(radiobutton) Large           Price
(radiobutton) Small           Price

"It'll recognize only radiobuttons. Other buttons won't be affected"
this is not the case if i use gird inside radiobuttongroupview.

Thanks in advance

**Comment by enisn** [comment]
If you want column view you can use selectionview, its easy way,

Try that:

```xml
               <input:SelectionView ColumnNumber="3" SelectionType="RadioButton" ColumnSpacing="4" SelectedItem="{Binding SelectedItem}">
                <input:SelectionView.ItemsSource>
                    <x:Array Type="{x:Type x:String}">
                        <x:String>Large Price</x:String>
                        <x:String>Small Price</x:String>
                        <x:String>Other Price</x:String>
                    </x:Array>
                </input:SelectionView.ItemsSource>
            </input:SelectionView>
```

<img src="https://scontent.fbtz1-1.fna.fbcdn.net/v/t1.15752-9/37258911_2012621642082272_1594158548785299456_n.png?_nc_cat=0&oh=4c1914b7b23a56fc942fa0ef9938c66b&oe=5BD3AC26" height="480" />

SelectedItem will return you "Small Price" as string.


---

Or you can bind ItemsSource for dynamic selections.

**Comment by Marium-Hashmi** [comment]
Thank you, I got it now.
One more thing 
while using 
public RadioButton(object value, string displayMember, bool isChecked = false);
to create a radio button, it shows result as follow:

![image](https://user-images.githubusercontent.com/33281835/42800680-42f0d5e0-89b6-11e8-9824-304a4cb5c762.png)

**Comment by enisn** [comment]
displayMember parameter means property name to display.
For example you have an class like that:

```csharp
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    }
```

And when creating RadioButton:


```csharp
    Product product = new Product { Id = 1, Name = "T-Shirt", Price = 20 };

            RadioButton rb = new RadioButton(product, "Name", false); //RadioButton's text will be Name property of object
            //It'll display T-Shirt
```

It'll display T-Shirt.

**Comment by Marium-Hashmi** [comment]
Thanks a lot for all your help 👍
