### ISSUE TITLE
Advanced Slider (range)

### ISSUE THREAD

**Issue by LeoJHarris** [enisn/Xamarin.Forms.InputKit#150]
Hi would be super cool to be able to have a range within the slider, something like the below

![android](https://user-images.githubusercontent.com/5468757/60781175-63519200-a195-11e9-92ee-7defbfecaacd.png)

**Comment by enisn** [comment]
Unfortunately AdvancedSlider is not suported ranges currently. 
I'm adding that to feature list. But I can't say when will be done.

**Comment by enisn** [comment]
Try this one: 
https://github.com/AndreiMisiukevich/RangeSlider.MAUI
