### ISSUE TITLE
CheckBox doesn't Work

### ISSUE THREAD

**Issue by Amalakalpana** [enisn/Xamarin.Forms.InputKit#154]
Hi,
I'm using Xamarin.Forms.InputKit.
While Click On CheckBox it Doesn't work Check/Uncheck Function, but when I click on Text It's working. I need to Click on the CheckBox Function.

I'm using this code,

                <StackLayout Spacing="0">
                    <input:CheckBox Type="Material" Text="Remember me"/>
                </StackLayout>

**Comment by enisn** [comment]
I've just checked. I couldn't catch the problem. Can you sahre more information about it? Which device or OS version?

**Comment by enisn** [comment]
Just checked again, it works:
![ezgif-7-21e5aa2dc9b1](https://user-images.githubusercontent.com/23705418/72924847-b4f0f100-3d62-11ea-9316-1d13ac412535.gif)

If  problem occurs again, please fee lfree to re-open this issue again
