### ISSUE TITLE
CheckBox Material - How to Change cross color

### ISSUE THREAD

**Issue by ThomasCurti** [enisn/Xamarin.Forms.InputKit#159]
Hi,

I have a project in Xamarin.

I have a lot of checkbox in a xaml view and I would like to have all of them with the option "material" and set the cross color to white.
However, when I set the material color to orange, the cross color is black, how can I change it to white ?

I tried to set the type to "Check" and set the Color to White and the BoxBackgroundColor to Orange. After the click a converter change the BoxBackgroundColor to White but I created a lot of bool values to bind with the converter and it's not really sexy ...

Regards

**Comment by enisn** [comment]
When you set a color following method decides which color will be cross or icon:
https://github.com/enisn/Xamarin.Forms.InputKit/blob/d294b5802b572b3eb7e1111d63330d5d4d1d6712/InputKit/Shared/Helpers/ColorExtensions.cs#L12

There is no Force color setting property for that.
I think **IconColor** or something like that will be enough for that.

**Comment by enisn** [comment]
@ThomasCurti 
**IconColor** is added to CheckBox in `v3.0.14`

**Comment by ThomasCurti** [comment]
Nice, thx
