### ISSUE TITLE
RadioButton Property "Value" bind Xamarin.Forms.Binding.

### ISSUE THREAD

**Issue by ErBhautik** [enisn/Xamarin.Forms.InputKit#16]
## My Question Here?
How to bind some value to RadioButton property Value.

### Also I tried that:
Whenever I bind something to value property it will always bind Xamarin.Forms.Binding object.
On Clicked or ClickCommand in Value property always get  Xamarin.Forms.Binding object

```xml
   <input:RadioButton Text="{Binding Name}" Value="{Binding Hobby}" />
```

**Comment by enisn** [comment]
If you need bind selection you can use IsChecked:

```xml
<input:RadioButton Text="{Binding Name}" IsChecked="{Binding Hobby}" />
```

<hr />
### Or 

If you need result from a list you can use like that:

```csharp
  private int _hobby;

        public int Hobby
        {
            get { return _hobby; }
            set { _hobby = value; OnPropertyChanged(); }
        }
```

And XAML:


```xml
            <input:RadioButtonGroupView SelectedIndex="{Binding Hobby}">
                <input:RadioButton Text="Football"  />
                <input:RadioButton Text="Baseball" />
                <input:RadioButton Text="Basketball" />
                <input:RadioButton Text="Tennis" />
            </input:RadioButtonGroupView>
```

You'll get SelectedIntex to your Hobby property.

<hr />
###  Or 

If you need ask selection from dynamic list you can use [SelectionView](https://github.com/enisn/Xamarin.Forms.InputKit/wiki/SelectionView). 
There is a sample for dynamic radio buttons. You can see it:
[Adding dynamicly Radio Buttons](https://github.com/enisn/Xamarin.Forms.InputKit/wiki/Adding-dynamicly-RadioButtons)

**Comment by enisn** [comment]
**CommandParameter** added to **RadioButton**, You can set the parameter now. If you don't set CommandParameter, It'll send autmaticly **Value** property as CommandParameter.  
It was itself of RadioButon before, fixed.

It's available on v.2.0.5 and you can find that version from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.0.5)

**Comment by ErBhautik** [comment]
Thanks
