### ISSUE TITLE
The type or namespace name 'Platforms' does not exist in the namespace 'Plugin.InputKit'

### ISSUE THREAD

**Issue by kumarvikram** [enisn/Xamarin.Forms.InputKit#161]
I am getting build error at following line in MainActivity.cs after upgrading to ver 3.0.13. Ver 3.0.12 is working fine. 

`Xamarin.Essentials.Platform.Init(this, savedInstanceState);`

It says 

> Error CS0234 The type or namespace name 'Platforms' does not exist in the namespace 'Plugin.InputKit' (are you missing an assembly reference?)

**Comment by enisn** [comment]
Are you targeting `monoandroid81` ?

**Comment by enisn** [comment]
https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v3.0.13
Monoandroid81 support is ended at v3.0.13 and can you try targeting to `monoandroid90` or above?

**Comment by kumarvikram** [comment]
Changing the target framework of Android project to Android P resolved this issue.

Thanks a lot.
