### ISSUE TITLE
RadioButton doesn't render in Android after I updated xamarin to 4.3

### ISSUE THREAD

**Issue by justwooper** [enisn/Xamarin.Forms.InputKit#165]
Hi, I have an app where I use this control and it was showing perfect, until I downloaded all lastes versión, from your tool and Xamarin and now is not rendering, what can I do? thanks

**Comment by enisn** [comment]
Can you check if there is a log from inputkit assembly in your output window?

**Comment by justwooper** [comment]
Using version 3.0.12 works great, I will keep this version until is fixed using greater version, thanks

**Comment by enisn** [comment]
I'm not sure what happens with Xamarin Forms 4.3, but it seems this issue is outdated.
