### ISSUE TITLE
Error while adding Init method to Xamarin.Android

### ISSUE THREAD

**Issue by ghost** [enisn/Xamarin.Forms.InputKit#167]
While Adding  Plugin.InputKit.Platforms.Droid.Config.Init(this, savedInstanceState); 
It's throwing error which mentioned below;

**Error	CS0234	The type or namespace name 'Platforms' does not exist in the namespace 'Plugin.InputKit' (are you missing an assembly reference?)**

**Comment by enisn** [comment]
What is your Linker settings? @Sattasundar

**Comment by Sattasundar** [comment]
Linker settings **"None"**

**Comment by MarcAlx** [comment]
As temp fix you can revert `Xamarin.Forms.InputKit` back to version `3.0.12` the latest version for me that does not throw this error.

**Comment by enisn** [comment]
> While Adding Plugin.InputKit.Platforms.Droid.Config.Init(this, savedInstanceState);
> It's throwing error which mentioned below;
> 
> **Error CS0234 The type or namespace name 'Platforms' does not exist in the namespace 'Plugin.InputKit' (are you missing an assembly reference?)**

It's all about your Target SDK version for Android.

InputKit currently supports Android 9, 10, and 11.

If you're using a different target framework that InputKit doesn't target, InputKit reference can't be included in your project. So if don't see that method, that means Renderers aren't included in your project, too.
