### ISSUE TITLE
CheckBox Check Changed Event

### ISSUE THREAD

**Issue by sirwes** [enisn/Xamarin.Forms.InputKit#17]
A feature to do something whenever a checkbox is unchecked or checked would be really nice. I see you have a CheckChangedCommand, but I don't think it's what I'm looking for. Correct me if I'm wrong.

I'm thinking it'd be something like this:
In the Xaml:
\<CheckBox x:Name="MyCheckBox" CheckChanged="MyFunction"/>

In the code:
...
public void MyFunction(object sender, EventsArgs e)
{
    print("CheckBox checked = ",MyCheckBox.IsChecked)
}
...

**Comment by enisn** [comment]
You can do something like that:

```csharp
       private void CheckBox_CheckChanged(object sender, EventArgs e)
        {
            if ((sender as CheckBox).IsChecked)
            {
                DisplayAlert("", "What a nice! You checked...", "OK");
            }
        }
    }
```
Events work basicly, and they don't sends custom EventArgs to methods. 

It's more compatible to use with MVVM.

**ClickCommand** sends itself of CheckBox as CommandParameter to your ViewModel.

**Comment by sirwes** [comment]
I understand. Thanks for the help!
