### ISSUE TITLE
Bug on AdvancedEntry when press return button on keyboard 

### ISSUE THREAD

**Issue by amer2737** [enisn/Xamarin.Forms.InputKit#171]
**Describe the bug**
when finished enter text and press enter button on keyboard the app crash  

**To Reproduce**
1. Go to 'AdvancedEntry'
2. Write on 'some text'
3. Click to 'Enter button on keyboard'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by enisn** [comment]
Can you share more information about it and some example code?
Where do you place AdvancedEntry and which type do you use?
