### ISSUE TITLE
Failed to set IconColor of Checkbox in xaml.

### ISSUE THREAD

**Issue by LITTOMA** [enisn/Xamarin.Forms.InputKit#179]
Tried to set IconColor in xaml like this:
``` xaml
<input:CheckBox x:Name="testCB" Grid.Column="0" Type="Material" IconColor="White" Color="#EFCC96" CornerRadius="20"/>
```
But failed:

>  No property, bindable property, or event found for 'IconColor', or mismatching type between value and property.

### Also I tried that:
Set IconColor in C# is ok:

```csharp
            var cb = (Plugin.InputKit.Shared.Controls.CheckBox)FindByName("testCB");
            cb.IconColor = Color.White;
```

**Comment by LITTOMA** [comment]
Hello, do you need more information for this issue?

**Comment by enisn** [comment]
@LITTOMA 
Yeah, problem occurs here, because bindable property type is nullable color (`Color?`).

https://github.com/enisn/Xamarin.Forms.InputKit/blob/c8b39b22434236af27aee5fbf23b9f02e825507b/InputKit/Shared/Controls/CheckBox.cs#L204

I'll make it simply `Color`.

**Comment by mphill** [comment]
This will crash the app if set like this in the App.xaml

            <Style TargetType="input:CheckBox">
                <Setter Property="IconColor" Value="White" />
             </Style>

With a native crash on iOS:

=================================================================
	Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

nvalid IL code in Xamarin.App:InitializeComponent (): IL_4597: newobj    0x0a0000cf


It appears to be related to this nullable color.  I suspect this is probably a bug with Xamarin Forms.

[public static readonly BindableProperty IconColorProperty = BindableProperty.Create(nameof(IconColor), typeof(Color?), typeof(CheckBox), null, propertyChanged: (bo, ov, nv) => (bo as CheckBox).UpdateColors());](url)

**Comment by enisn** [comment]
The PR #208 solved this
