### ISSUE TITLE
AdvancedEntry Unfocused event doesn't work

### ISSUE THREAD

**Issue by kissurda** [enisn/Xamarin.Forms.InputKit#180]
I created AdvancedEntry in code behind, I subscribed Unfocused event, but didn't work.
Here is my code:

var entry = new AdvancedEntry()
                        {
                            BindingContext = item,
                            ClassId = qItem.QuestionId.ToString(),
                            TextColor = Color.Black,
                            Keyboard = Keyboard.Default,
                            Margin = new Thickness(10)
                        };
entry.Unfocused += Entry_Unfocused;

private void Entry_Unfocused(object sender, FocusEventArgs e)
{
}

**Comment by enisn** [comment]
Those events are inherited from `View` and can't be overriden or invoked. So the PR #213 includes new events & commands implementation which hides base events.
