### ISSUE TITLE
AdvancedEntry Annotation RegEx not working

### ISSUE THREAD

**Issue by DK99** [enisn/Xamarin.Forms.InputKit#181]
**Describe the bug**
The bug is that the IsAnnotated Property only checks if the RegEx has one match in the entered Entry. But the RegEx for LetterOnly, NonDigits, DigitsOnly only match a single character. So for example if I would enter "12ABC" in an Entry which has the Annotation set to DigitsOnly, it would return true because the RegEx "[0-9]" matches this string. The same would work for Decimal.

The Decimal has also the Problem of not matching "1.12" because you forget to pu brackets there.

Also I don't quite get, why you decided a Decimal can only have two digits after the Point.

**To Reproduce**
1. Open the Sample App
2. Open the AdvancedEntry Page
3. Type "Test123" inside the Name Entry. It should be NonDigitsOnly

**Expected behavior**
The Annotation should appear and say "Please type your name correctly".

**Screenshots**
![photo5395389796601408692](https://user-images.githubusercontent.com/5883283/75630437-11112580-5beb-11ea-863d-e4ec68e19ae2.jpg)

**Smartphone:**
 - Device: Multiple Devices and Emulator
 - OS: Android 9.0

**Additional context**
I will add a Pull Request later to deal with the Problem

**Comment by enisn** [comment]
Released in [v3.2.0](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.2.0)
