### ISSUE TITLE
AdvancedEntry add primitive Data Types as Annotation

### ISSUE THREAD

**Issue by DK99** [enisn/Xamarin.Forms.InputKit#183]
**Is your feature request related to a problem? Please describe.**
My Problem was, that I wanted to take an AdvancedEntry as an Input for an Int. But the RegEx Version only checks if the entered text is a Number. So the Entered Number could be too long for an Int. The same goes for other types like byte, sbyte and so on.

**Describe the solution you'd like**
I already programmed my solution. The solution is to add the relevant types to the AnnotationType Enum and check in the IsAnnotated method if you can parse the given text to this type.
Also I needed a method to allow empty Strings as an Entry so I added a Nullable Option too.

**Comment by enisn** [comment]
Included in [v3.2.1](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.2.1)

**Comment by DK99** [comment]
Are you sure? I don't think it is in 3.2.1.

**Comment by DK99** [comment]
Included in [v3.2.2](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.2.2)
