### ISSUE TITLE
CheckChangedCommand dont working

### ISSUE THREAD

**Issue by Informatheus** [enisn/Xamarin.Forms.InputKit#186]
**View:**
`xmlns:input="clr-namespace:Plugin.InputKit.Shared.Controls;assembly=Plugin.InputKit"`
...
`<input:CheckBox Type="Check" VerticalOptions="Center" CheckChangedCommand="{Binding CommandCheckChanged}"  IsChecked="{Binding Checked}" Color="{StaticResource CorAccent}"/>`

**ViewModel:**
`public Command CommandCheckChanged { get; set; }
`
...
`CommandCheckChanged = new Command(ActionCheckChanged);
`
...
`
public void ActionCheckChanged(object obj) {
            MyDataBase.Update(obj as Item);
        }
`

**Method ActionCheckedChanged is never called.**

**Comment by Kevin-Net** [comment]
I am having the same issue.. CheckChangedCommand not firing.. any update on this? Thanks.

**Comment by Kevin-Net** [comment]
nevermind.. it is working now.. I cannot use CheckChangedCommand="{Binding CommandCheckChanged}" . I need to change CheckChangedCommand="{Binding Path=BindingContext.CommandCheckChanged, Source={x:Reference Name=MyPageName}} "

**Comment by enisn** [comment]
@Kevin-Net @Informatheus 

I think problem occurs at following line:
https://github.com/enisn/Xamarin.Forms.InputKit/blob/414572c7f9c9dac2e6b43a353706010e4857de7b/InputKit/Shared/Controls/CheckBox.cs#L245

CanExecute is null and default value is false. So, I'm changing default value as true and command will be executed when CanExecute is null.

**Comment by enisn** [comment]
Commit b9cf892 should solve the problem. Can you check [v3.3.0-pre.2](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.3.0-pre.2) and above.

Feel free to re-open this issue if it doesn't work.
