### ISSUE TITLE
Hope there is a parameter to control the imgArrow in DropDown

### ISSUE THREAD

**Issue by LinuxAndOracle** [enisn/Xamarin.Forms.InputKit#187]
Your control is very helpful to me. I want to ask if there is a parameter that can control the size of imgArrow in DropDown, or which parameter can be controlled. I hope to get an answer, thank you

**Comment by prajaktashindeSilicus** [comment]
+1

**Comment by enisn** [comment]
After commit 414572c 

You have two option. 
## First option
Use ArrowIcon property:
```xml
<input:Dropdown ArrowIcon="my_arrow_icon" />
```

## Second option
You can use following code:
```csharp
    public class MyDropdown : Dropdown
    {
        public MyDropdown()
        {
            imgArrow.WidthRequest = 40;
            imgArrow.HeightRequest = 40;
        }
    }
```

Inherit from `Dropdown` and make changes on **imgArrow** as you wish. This field is `protected` now after [v3.3.0-pre.1](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.3.0-pre.1)
