### ISSUE TITLE
SelectedItemChangedCommand not firing event

### ISSUE THREAD

**Issue by pmahend1** [enisn/Xamarin.Forms.InputKit#188]
**Describe the bug**
`SelectedItemChangedCommand` not firing event in MVVM approach.

**To Reproduce**
```xml
<inputkit:RadioButtonGroupView SelectedItemChangedCommand="{Binding PhoneorEmailSelectionChangedCommand}" 
                               CommandParameter="{Binding Source={RelativeSource Self}, Path=SelectedIndex}" 
                               x:Name="phoneOrEmailRadioGroup">
    <inputkit:RadioButton Text="{Binding PhoneNumber}" 
                          CircleSize="50" 
                          VerticalOptions="Center" 
                          TextFontSize="Body" />
    <inputkit:RadioButton Text="{Binding Email}" 
                          CircleSize="50" 
                          TextFontSize="Body" 
                          VerticalOptions="Center" />
</inputkit:RadioButtonGroupView>
```

In ViewModel its not firing event

```csharp
PhoneorEmailSelectionChangedCommand = new Command<int>((index) => ChangeVerificationMethod(index));
```

If I do this in code behind it works 

```csharp
phoneOrEmailRadioGroup.SelectedItemChanged += RadioGroup_SelectedItemChanged;

     
private void RadioGroup_SelectedItemChanged(object sender, System.EventArgs e)
{
    var rg = sender as RadioButtonGroupView;
    _ViewModel.PhoneorEmailSelectionChangedCommand.Execute(rg.SelectedIndex);
}
```

Please check and suggest if issue in my approach

**Expected behavior**
`SelectedItemChangedCommand` should work with a `CommandParameter` in MVVM

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: Anroid 
 - OS: Q(10) APK 29
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by enisn** [comment]
Yeah, The problem occurs when command doesn't have CanExecute method. At the following line, default value is false if CanExecute is null:
https://github.com/enisn/Xamarin.Forms.InputKit/blob/b9cf8924beb5763f8602e07f4277027534409831/InputKit/Shared/Controls/RadioButtonGroupView.cs#L173-L174

I'm making it `true` as default.

**Comment by enisn** [comment]
@pmahend1 

 It should be solved after commit 218c3c0
Can you check [v3.3.0-pre.3](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.3.0-pre.3) or above.

Feel free to re-open this issue if it'll not work.

**Comment by pmahend1** [comment]
> 
> 
> Yeah, The problem occurs when command doesn't have CanExecute method. At the following line, default value is false if CanExecute is null:
> 
> https://github.com/enisn/Xamarin.Forms.InputKit/blob/b9cf8924beb5763f8602e07f4277027534409831/InputKit/Shared/Controls/RadioButtonGroupView.cs#L173-L174
> 
> I'm making it `true` as default.

You mean manually define `CanExecute()?` since `PhoneorEmailSelectionChangedCommand`  is `Command` not ICommand by default its implemented with the action,
I had passed non null `CommandParameter`

**Comment by pmahend1** [comment]
I tried this in latest stable 3.3.0 and 3.3.0-pre3 version. Both do not fire the Command unfortunately.
