### ISSUE TITLE
checkbox kanda CheckType.Box can not change the Color

### ISSUE THREAD

**Issue by charcoalditto** [enisn/Xamarin.Forms.InputKit#19]
**Expected behavior**
inner box's color should be black

**Screenshots**
<img width="498" alt="2018-07-31 8 21 55" src="https://user-images.githubusercontent.com/26886129/43456699-70949dca-94ff-11e8-8fea-f41ad8974534.png">

**Smartphone (please complete the following information):**
 - Device: android virtual device
 - OS: Oreo, Api 27
 - Browser
 - Version

**Comment by enisn** [comment]
Can I see your XAML code, 

I think a bindable property does not trigger other, try change order properties like:

from: 

Type="Check"
Color="Blue"

To:

Color="Blue"
Type="Check"


I'll fix that problem on newer versions.

**Comment by enisn** [comment]
If you use same color in all your app, 
You can try this:

in you **App.cs**

```csharp
Plugin.InputKit.Shared.Controls.CheckBox.GlobalSetting.Color = Color.Blue;

```

It'll be applied all the CheckBoxes

**Comment by kubaizi** [comment]
Plugin.InputKit.Shared.Controls.RadioButton.GlobalSetting
not working for me
i try deleting bin/obj
still not working

**Comment by enisn** [comment]
> Plugin.InputKit.Shared.Controls.RadioButton.GlobalSetting
> not working for me
> i try deleting bin/obj
> still not working

You need to use that before setting MainPage in **App.cs**,
