### ISSUE TITLE
Adjusting space between checkboxes and Radio Buttons in Selection view

### ISSUE THREAD

**Issue by sylendra7** [enisn/Xamarin.Forms.InputKit#190]
How to adjusting space between checkboxes and Radio Buttons in Selection view

**Comment by enisn** [comment]
@sylendra7 
Have you tried `ColumnSpacing` and `RowSpacing` property ?
SelectionView inherits theses properties from **Grid**. _([Xamarin.Forms.Grid](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid))_

```xml
            <input:SelectionView
                ColumnNumber="2"
                ColumnSpacing="10"
                RowSpacing="10"
                ItemDisplayBinding="{Binding Name}"
                ItemsSource="{Binding MyList}"
                SelectionType="CheckBox" />
```
