### ISSUE TITLE
Set AdvEntry border color as a property to bind it in Styles

### ISSUE THREAD

**Issue by dsancho** [enisn/Xamarin.Forms.InputKit#191]
public static readonly BindableProperty BorderColorProperty = BindableProperty.Create(nameof(BorderColor), typeof(Color), typeof(AdvancedEntry), Color.Default, propertyChanged: (bo, ov, nv) => (bo as AdvancedEntry).BorderColor = (Color)nv);

**Comment by enisn** [comment]
I think this issue is no longer open,

https://github.com/enisn/Xamarin.Forms.InputKit/blob/0a29e0b7ee392ff2b9aa5afef0c2a2f119708e6b/InputKit/Shared/Controls/AdvancedEntry.cs#L421

BindableProperty is exist at latest version
