### ISSUE TITLE
AdvancedEntry cursor position

### ISSUE THREAD

**Issue by Haza85** [enisn/Xamarin.Forms.InputKit#192]
Is exist any way to set cursor position in AdvancedEntry?

**Comment by enisn** [comment]
Unfortunately, there is no way to set or get this option. 😕
@Haza85 
--
If Xamarin Forms implement that feature, This library can provide it, too

**Comment by Haza85** [comment]
Cursor position have Entry in XamarinForms. But AdvancedEntry is not extend Entry control. Sorry, but I not see how could I set position.

**Comment by enisn** [comment]
I've just moved it into feature development plan. I't willb e developed as soon as possible. @Haza85

**Comment by Haza85** [comment]
Thank you
