### ISSUE TITLE
AndroidX not supported and show error 

### ISSUE THREAD

**Issue by rajagemini** [enisn/Xamarin.Forms.InputKit#194]
I have upgrade the Xamarin form application to AndroidX and XF4.5. Currently I have XF inputkit 3.3.0. I am getting below compile time error. 

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Error XA2002: Can not resolve reference: `Xamarin.Android.Support.Design`, referenced by `Plugin.InputKit`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.Design`, or remove the reference to `Plugin.InputKit`. (XA2002) 

I am using VS 2019 for mac. Does InputKit depend on Xamarin.Android.Support.Design?. How can I use AndroidX with InputKit?

**Comment by acuntex** [comment]
Just a small note: Beginning from November 2nd google will not accept any apps below level 29 (Android 10).

Which means that all users of this library will probably have a hard time.

**Comment by enisn** [comment]
AndroidX Support is released with #203
