### ISSUE TITLE
SelectionView, SelectionType Button, deselect by tapping again

### ISSUE THREAD

**Issue by smuuba** [enisn/Xamarin.Forms.InputKit#196]
For the selection type of MultipleButton, it is possible to deselect an option by tapping on it again.  This does not seem to be available for the Button selection type.  Am I missing something?  If it is not there could it be added, or perhaps point me to a way to tie into the tapped event of the buttons in the list?  Thanks

**Comment by enisn** [comment]
Yeah, it's really necessary feature. I'm putting it to Feature Development board.

**Comment by enisn** [comment]
@smuuba 
As I understand you asked for unselecting a button:
It seems 'SelectionView' already has that feature when you use as MultipleButton option:

![video-1600109003](https://user-images.githubusercontent.com/23705418/93125253-851ca200-f6d3-11ea-8ccc-c22c3c853412.gif)

But there is no option to use that feature in Button type. You can make your custom **SelectionView** and override GetInstance() method for make it happen:

```csharp
    public class MySelectionView : SelectionView
    {
        public override ISelection GetInstance(object obj)
        {
            if (this.SelectionType == SelectionType.Button)
            {
                return new SelectableButton(obj, this.Color)
                {
                    CanChangeSelectedState = true
                };
            }
            return base.GetInstance(obj);
        }
    }
```

Then use your selectionView:


```xml

<controls:MySelectionView SelectionType="Button">
    <!-- Something here ... -->
</controls:MySelectionView>
```

**Comment by smuuba** [comment]
Thanks for your response and suggestion.  I am trying to implement it but I
am getting this:

[image: image.png]

Any thoughts on how I can get around this?

Thanks

**Comment by enisn** [comment]
@smuuba I'm sorry, that was my mistake. SelectableButton was internal and you couldn't use it. 

Can you try again after [v3.4.1](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.4.1) update?
