### ISSUE TITLE
Missing of Corner radius and Border color in Selection view

### ISSUE THREAD

**Issue by arjun-cn** [enisn/Xamarin.Forms.InputKit#199]
Its complicated to adjust with UI of the seletion view that due to the lack of corner radius and Border color property .

**Comment by enisn** [comment]
There isn't any feature something like that,

But you can try create your own SelectionView and override GetInstance method as your wish:

```csharp
    public class MySelectionView : SelectionView
    {
        public override ISelection GetInstance(object obj)
        {
            if (this.SelectionType == SelectionType.Button || this.SelectionType == SelectionType.MultipleButton)
            {
                return new SelectableButton(obj, this.Color)
                {
                    CornerRadius = 20 // Put your customizations here...
                };
            }
            return base.GetInstance(obj);
        }
    }
```

Then you can use your **MySelectionView** at your XAML pages:

```xml
<controls:MySelectionView SelectionType="Button" ItemsSource="{Binding YourSource}"/>
```


> **REMEMBER:** Overriding GetInstance() is available after [v3.4.1](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.4.1).
