### ISSUE TITLE
Unable to Add Nuget package to my project

### ISSUE THREAD

**Issue by Parmendrakumar** [enisn/Xamarin.Forms.InputKit#2]
I am using VS 2015 and nuget successfully install on Android and iOS but getting issue on PCL

Getting issue: Could not install package 'Xamarin.Forms.InputKit 0.9.8'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by enisn** [comment]
I think the problem is target .Net Standard version, 
This package was packed on .Net Framework 4.6.1 and it targets .Net Standard 2.0+
You can try to upgrade your project target and dependencies too
