### ISSUE TITLE
input:AdvancedEntry not rounded off at the edges properly in IOS . 

### ISSUE THREAD

**Issue by ShamineDsouza** [enisn/Xamarin.Forms.InputKit#200]
input:AdvancedEntry Control for entering text  is not rounded off at the edges properly in IOS . 
One side remains boxed while the other partially rounded .
Works perfectly in android.
Android :
![IMG_20200920_141637](https://user-images.githubusercontent.com/25946929/93710076-64799f80-fb4c-11ea-8761-a45bf42d0602.jpg)

IOS Not displaying properly
![IMG_20200920_141654](https://user-images.githubusercontent.com/25946929/93710085-7bb88d00-fb4c-11ea-90bd-1690c046cbe8.jpg)

Visual studio 2019

**Comment by enisn** [comment]
Can share device info? 
I need to find screen size & OS version

**Comment by ShamineDsouza** [comment]
iPhone 11 emulator
iOS 13.6

**Comment by ShamineDsouza** [comment]
Hi, by when can I expect this to be done ? Since we are in a hurry to deploy our app for testing next week and then launch it a week after .Hence the urgency.

**Comment by enisn** [comment]
@ShamineDsouza 
I'm sorry I can't recognize problem, but it seems all about default background colors of some views.
Can you try [v3.4.2-pre.1](https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.4.2-pre.1) ?

**Comment by ShamineDsouza** [comment]
This is not available on nuget . Latest is 3.4.1

**Comment by ShamineDsouza** [comment]
Thank you . I was able to implement the prerelease .  And it is fine now the design  . The control appears properly.

However , there is an issue with , text alignment in IOS . 
Dropdown text remain left aligned
TextBox remain right aligned , irrespective of language .
It works fine in Android . 
Should I raise a another issue request for the same ?

**Comment by enisn** [comment]
Sorry my late reply, as you said that version was pre-release. If it works properly, I can publish it as a full version.
I'll open a new issue about your last request.
