### ISSUE TITLE
Expose FontFamily property for checkbox in xaml style

### ISSUE THREAD

**Issue by SagarPanwala** [enisn/Xamarin.Forms.InputKit#204]
Similar fix to #98 .
This is fixed for RadioButton but not for Checkbox.
I'm on latest stable version 3.4.3

**Comment by enisn** [comment]
Might be solved with new version [v3.4.4](/enisn/Xamarin.Forms.InputKit/releases/tag/v3.4.4).
---

Feel free to re-open this issue if issue continues.
