### ISSUE TITLE
AdvancedEntry cannot be changed from AnnotationType.Password to a different value

### ISSUE THREAD

**Issue by DeanoMartino** [enisn/Xamarin.Forms.InputKit#21]
Setting AnnotationType on AdvancedEntry to 'Password' will effectively hide the contents of the entry with black dots but if you change the AnnotationType at runtime to a different value, the entry contents remain as black dots.

Envision a scenario where the AdvancedEntry is used to enter a password and the AnnotationType property is data-bound with a default value of Password.  The user taps an 'eye' icon to toggle the display of the password value.  The toggle operation should be able to simply change the AnnotationType value but this fails.  

The problem is identified in the UpdateKeyboard() method.  This works fine when first setting the AnnotationType to password and txtInput.IsPassword is set to true .  But from that point on txtInput will always have its IsPassword property set to true.  It is never set to false for the other annotation types and so the entry will always display black dots.

**Comment by enisn** [comment]
It'll be fixed

**Comment by enisn** [comment]
It was solved at[ v.2.1.0 Material Base Release](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.1.0). 
You can find on Nuget v 2.1.0 version from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.1.0)
