### ISSUE TITLE
Is CheckCommandParameter exist, if not please add

### ISSUE THREAD

**Issue by logeshpalani33** [enisn/Xamarin.Forms.InputKit#218]
**Is your feature request related to a problem? Please describe.**
I can't find the checkbox CheckCommandParameter in Checkbox control, please add it, if already exist update document

**Comment by enisn** [comment]
You can use `CommandParameter`. It will be sent as parameter to CheckCommand.

---

https://github.com/enisn/Xamarin.Forms.InputKit/blob/af149c3ab9f28a69de6c0e57ef05482411f1cb0a/InputKit/Shared/Controls/CheckBox.cs#L260-L264

**Comment by logeshpalani33** [comment]
yeap, i got it. thanks team
