### ISSUE TITLE
Checkbox Material type background always white, how to change that?

### ISSUE THREAD

**Issue by logeshpalani33** [enisn/Xamarin.Forms.InputKit#219]
## My Question Here ?
Checkbox Material type background always white, how to change that?

### Also I tried that:
i tried to change BoxBackgroundColor and IconColor, but these two are not working 

```xml
    <input:CheckBox Grid.Column="3"
                        BoxBackgroundColor="Red"
                        CheckChangedCommand="{Binding Source={RelativeSource AncestorType={x:Type localViewmodel:AttendancePageViewModel}}, Path=Mark_AttendanceCommand}"
                        BoxSizeRequest="30"
                        Type="Material"
                        IconColor="Red"
                        IsChecked="{Binding CurrentSessionDetail.IsSelected}"
                        IsDisabled="{Binding Source={RelativeSource AncestorType={x:Type localViewmodel:AttendancePageViewModel}}, Path=IsAttendanceEnabled, Converter={StaticResource inverseConverter}}"/>
```

**Comment by enisn** [comment]
Hi @logeshpalani32 

With Material type, `Color` property will be used to tint checkbox background when **selected**,
otherwise `Color` property will be used as border color when **unselected**.

Following code produces checkboxes in picture:
```xml
<input:CheckBox
        BoxSizeRequest="30"
        Type="Material"
        Color="Red"
        IconColor="White"/>
<input:CheckBox
        BoxSizeRequest="30"
        Type="Material"
        Color="Red"
        IconColor="White"
        IsChecked="True"/>

```

![image](https://user-images.githubusercontent.com/23705418/128472342-473e6cae-8eab-45e6-9d4f-a3f41fd2b5bb.png)

**Comment by logeshpalani33** [comment]
Naming are hard to understand that why i raised this question thanks for immediate response and try to update proper documentation for all types
