### ISSUE TITLE
AdvancedEntry needs a few more bindings and events

### ISSUE THREAD

**Issue by DeanoMartino** [enisn/Xamarin.Forms.InputKit#22]
AdvancedEntry:  needs bindings for IsRequired and ValidationMessage properties.
AdvancedEntry:  needs a TextChanged event.

**Comment by enisn** [comment]
They'll be added as soon as possible.

**Comment by enisn** [comment]
They added at [v.2.2.0](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.2.0) release,

You can find changelog from [here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.2.0)
