### ISSUE TITLE
Dropdown needs binding for AnnotationColor

### ISSUE THREAD

**Issue by DeanoMartino** [enisn/Xamarin.Forms.InputKit#23]
These are really nice controls and I appreciate the on-going maintenance.  I've noticed the AdvancedEntry control has a binding for AnnotationColor but the Dropdown does not.  Can this be added?  Thanks!

**Comment by enisn** [comment]
Dropdown is  a new control. I couldn't completed yet, It's like a demo. I'll add much more bindable Properties as soon as possible

**Comment by enisn** [comment]
@DeanoMartino  

**AnnotationColor** and much more **BindableProperties** added on [v.2.2.1 release](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.2.1).

Nuget version is [here ](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.2.1)too.

Have a nice work. 👍
