### ISSUE TITLE
Advanced Slider - Can only bind to Value

### ISSUE THREAD

**Issue by GaborTheHutt** [enisn/Xamarin.Forms.InputKit#245]
**Describe the bug**
I can only bind to the value property.

It would be great if the other propertys would be bindable as well.

**Comment by GaborTheHutt** [comment]
thx.
Color Property and a Drag Complete and  a DragCompleted Event would be nice too :)

**Comment by enisn** [comment]
I've been working on infrastructural work for supporting both XF and Maui at the same time.  Now there is no a possible way to publish v3.8

I'm moving this issue to v4.0
