### ISSUE TITLE
Checkbox have unwanted shadow on iOS

### ISSUE THREAD

**Issue by yudiz-mahavir** [enisn/Xamarin.Forms.InputKit#25]
**Bug** : Checkbox shows unwanted shadows around them

**To Reproduce** : Happens everytime on iOS

**Expected behavior** : There should be no shadow or an option to toggle shadow

**Smartphone (please complete the following information):**
 - Device: iPhone 5c
 - OS: iOS 10.3.3
 - InputKit Version : 2.2.1

**Screenshot**
![shadow issue](https://user-images.githubusercontent.com/11229222/43759789-f127ecb0-9a3d-11e8-86b8-bd21fe247938.PNG)

**Comment by enisn** [comment]
I think it happens by Framerenderer when the background is Transparent, 
I'll solve that problem as soon as possible,

**Comment by yudiz-mahavir** [comment]
here is my code :
`  <input:CheckBox Text="{Binding LabelItem}" TextFontSize="14" Type="Check" BackgroundColor="Transparent" Color="{StaticResource YetiBlue}" BorderColor="{StaticResource YetiBlue}" />`

**Comment by enisn** [comment]
@yudiz-mahavir 

It is solved at [v.2.2.2 release](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.2.2).

You can find new version on Nuget from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.2.2)
