### ISSUE TITLE
SelectionView - SelectedIndex & SelectedIndexes Properties needed

### ISSUE THREAD

**Issue by toyins46** [enisn/Xamarin.Forms.InputKit#26]
SelectedIndex Bindable property is needed for the RadioButton
SelectedIndexes Bindable property is needed for the CheckBoxes.

**Comment by enisn** [comment]
@toyins46  Finally SelectionView has SelectedIndexes now with [v.2.3.0 Release](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.0). 

Nuget is available [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/).

**Comment by toyins46** [comment]
Thanks Enis.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
