### ISSUE TITLE
BoxBackgroundColor equivalent for RadioButton?

### ISSUE THREAD

**Issue by greg84** [enisn/Xamarin.Forms.InputKit#263]
With a CheckBox I can set BoxBackgroundColor to change the colour of the background of the box.

Is there a way to do something similar with a RadioButton? I would like to change the colour of the background inside the circle.

**Comment by enisn** [comment]
You can set your custom image to achieve that, RadioButton doesn't have that kind of feature at the moment.
  ```xml
    <input:RadioButton Text="Option 1" CircleImage="my_custom_circle_with_background.png" />
  ```

**Comment by enisn** [comment]
This image is used at the moment:
https://github.com/enisn/Xamarin.Forms.InputKit/blob/develop/src/InputKit.Maui/Shared/Resources/circle.png

I'll convert all the resources to `svg` format soon. After that, it'll be possible to set background color separately

**Comment by greg84** [comment]
Thanks @enisn! Not sure why I didn't think of that. Makes perfect sense!
