### ISSUE TITLE
MAUI: Accepting FontImageSource in InputKit Controls

### ISSUE THREAD

**Issue by sattasundar** [enisn/Xamarin.Forms.InputKit#264]
Controls need to accept FontImageSource to support FontIcons. This will give more flexibility to developer.

e.g.
 
           <inputKit:AdvancedEntry BorderColor="{DynamicResource AccentColor}"
                                    BackgroundColor="Transparent"
                                    CornerRadius="10"
                                    Placeholder="Username">
                <inputKit:AdvancedEntry.IconImage>
                    <FontImageSource FontFamily="IconFontTypes"
                                             Glyph="{x:Static helpers:IconFont.AccountOutline}"
                                             Color="{DynamicResource AccentColor}">
                    </FontImageSource>
                </inputKit:AdvancedEntry.IconImage>
            </inputKit:AdvancedEntry>

**Comment by enisn** [comment]
This is a good option. This feature is missing because I've just migrated from Xamarin Forms.

We can add it to the MAUI implementation 👍

**Comment by enisn** [comment]
After PR #285, FontIcon can be used in version `4.1.0`

4.1 stable hasn't released yet but you can go with `4.1.0-pre.1`
