### ISSUE TITLE
Dropdown Title - Text size

### ISSUE THREAD

**Issue by LeoJHarris** [enisn/Xamarin.Forms.InputKit#28]
Hi not sure if its possible but couldnt find a property on the label for the drop down to change the title text size... Can consider exposing this property on the label?

**Comment by enisn** [comment]
I'll work on it as soon as possible 👍

**Comment by LeoJHarris** [comment]
Thanks, great work on the plugins btw :)

**Comment by mxstudios** [comment]
@enisn,

I also need this and may do it today. If you haven't started it, I can send you the code if I complete it. I also am working on setting the placeholder color to match the entry view, since you are actually simulating a placeholder.

**Comment by LeoJHarris** [comment]
@mxstudios Go for Gold I say :)

**Comment by LeoJHarris** [comment]
@enisn Still planning on adding the feature..? Any ETA?

**Comment by enisn** [comment]
I can not Build project anymore. I tried remote server to build but it didn't affect. I'm waiting support from MsBuild. If I can build the project, I'll update nuget, too

**Comment by enisn** [comment]
Added **TextFontSize** property  to Dropdown at v2.3.6. You can use now like below;

```xml
<inputKit:Dropdown Title="Hello World!" TitleFontSize="Large" />
```
<hr />
@LeoJHarris 

You can visit new version(2.3.6) from [here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/2.3.6). 
or
You can use NuGet package from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.6).
