### ISSUE TITLE
Drop down selected item changed - get Selected Value

### ISSUE THREAD

**Issue by LeoJHarris** [enisn/Xamarin.Forms.InputKit#29]
Hi again, I see you have a SelectedItem on the dropdown, is there some event that can be invoked when a user selects an option from the dropdown list and then check the SelectedItem perhaps in a event?

**Comment by LeoJHarris** [comment]
Working:

`SelectPaymentDropDown.ValidationChanged += (s, e) =>
                {
                    if (s is Dropdown dropdown && dropdown.ItemsSource?.Count >= 1)
                    {
                        if (dropdown.SelectedItem.ToString() == "New Card")
                        {
}
}
}`

**Comment by LeoJHarris** [comment]
That would be appreciated

**Comment by enisn** [comment]
@LeoJHarris 
**SelectedItemChanged** event added to Dropdown now.
It's included [v.2.3.4](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.4)
