### ISSUE TITLE
Unexpected Layout on Android Device

### ISSUE THREAD

**Issue by MickyCik** [enisn/Xamarin.Forms.InputKit#298]
It is my first time working with XF InputKit, I have installed the latest version but i did not get the expected layout as shown in the docs for advancedentry... see the attached screenshot
![Screenshot_20220909-050226](https://user-images.githubusercontent.com/52924459/189263816-a9735fe9-3a40-4955-87b4-6b0b0b5d89cd.png)
any suggest on what can cause this...??

**Comment by enisn** [comment]
Hi @MickyCik 

Can you provide info about which version are you using?

Do you use 4.x or 3.x version?

**Comment by enisn** [comment]
Grid children's behaviors are slightly different between MAUI and Xamarin Forms.

To it should be fixed on `v4.0.1`, you can upgrade to 4.0.1

**Comment by MickyCik** [comment]
> Hi @MickyCik
> 
> Can you provide info about which version are you using?
> 
> Do you use 4.x or 3.x version?

the latest 4.0.0

**Comment by MickyCik** [comment]
> Grid children's behaviors are slightly different between MAUI and Xamarin Forms.
> 
> To it should be fixed on `v4.0.1`, you can upgrade to 4.0.1

I will try this and get back to you

**Comment by enisn** [comment]
https://www.nuget.org/packages/Xamarin.Forms.InputKit/4.0.1
