### ISSUE TITLE
change background color of checkbox

### ISSUE THREAD

**Issue by mo-kml** [enisn/Xamarin.Forms.InputKit#3]
box background color is gray and i want to make it white with border
please add this feature to this package

![capture](https://user-images.githubusercontent.com/14197053/39968718-e744378e-56e6-11e8-945d-b3cb128fcf95.PNG)

**Comment by enisn** [comment]
Finally border support added the nuget package in **v.1.2.0** and above.

I think your desire is can be obtain with:

```xml
   
            <input:CheckBox Text="SUBSCRIBE TO OUR NEWSLETTER" Type="Check" BorderColor="Black" Color="Green"/>
            <input:CheckBox Text="Option 2" Type="Check" BorderColor="Black" Color="Green"/>
            <input:CheckBox Text="Option 3" Type="Check" BorderColor="Black" Color="Green"/>
```

And it'll be look like:

<img src="https://scontent-frx5-1.xx.fbcdn.net/v/t1.15752-0/p280x280/36975132_2003658502978586_1393598290620055552_n.png?_nc_cat=0&oh=d91ff852db64d6b16ee99c5949d26042&oe=5B46F9FB" height="500"/>
