### ISSUE TITLE
'Editable' Drop Down

### ISSUE THREAD

**Issue by stewartsims** [enisn/Xamarin.Forms.InputKit#30]
**Describe the solution you'd like**
A drop-down which has a property 'Editable' which when set to true would allow the user to enter their own text value. Essentially this would make the component a hybrid between a drop-down / picker and an entry.

**Comment by enisn** [comment]
It's Perfect idea 💡👌
After completely iOS implementation I'll do it.

**Comment by enisn** [comment]
@stewartsims Dropdown has **IsEditable** property now with [v.2.3.0 Release](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.0). You can get users custom input via **Text** property of Dropdown. 

Nuget is Avalable [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/).
