### ISSUE TITLE
Checkbox rendering wrong size when text is too long

### ISSUE THREAD

**Issue by kxgonzalez** [enisn/Xamarin.Forms.InputKit#319]
**Describe the bug**
When having a text that is multiple lines long the height of the checkbox is affected.

**Platforms tested**
- iOS Simulator: iPhone 14 Pro Max (iOS 16.0)
- Android Emulator: Android 13 (API 33)
- Physical device: iPhone 13 (iOS 15.6)
- Physical device: Motorola Edge 20 (Android 12 - API 31)

**To Reproduce**
1. Add a checkbox with a basic styling.
2. Add a very long text to it.
4. See the box filling all the vertical space.

**Expected behavior**
A square checkbox always. No matter how long the text is.

**Screenshots**
Current result with long text
![checkbox-1](https://user-images.githubusercontent.com/31975089/197014730-5bcd5c9d-a78a-4357-849d-be6828faba92.png)

After using a workaround
Setting `outlineBox.VerticalOptions = new LayoutOptions(LayoutAlignment.Center, false);` in `/src/Xamarin.Forms.InputKit/Shared/Controls/CheckBox.cs`

Still seeing an issue but better than before.
![checkbox-2](https://user-images.githubusercontent.com/31975089/197015044-03311571-e1ba-435c-b1e6-399e406fc063.png)

**Desktop:**
 - MacOS Monterey
 - Version: 12.6.0

**IDE:**
 - Visual Studio 2022 for Mac
 - Version: 17.3.6 (build 20)
 
**Xamarin:**
 - Xamarin.Forms 5.0.0.2515
 - Xamarin.iOS 16.0.0.72
 - Xamarin.Android  13.0.0.0

**Comment by enisn** [comment]
This issue seems it was started happening after merging #269
