### ISSUE TITLE
Dropdown selection not working on a modal page in iOS

### ISSUE THREAD

**Issue by mxstudios** [enisn/Xamarin.Forms.InputKit#32]
When the page that the dropdown is on a page that is modal, an error is thrown when selecting an item. The reason is that it is not finding the topmost view controller.

I fixed this by changing  line 35 in MenuEffect.cs:

RootController = UIApplication.SharedApplication.KeyWindow.RootViewController;

to:

 RootViewController = GetVisibleViewController();

And added this function:

 ```
UIViewController GetVisibleViewController()
        {
            var rootController = UIApplication.SharedApplication.KeyWindow.RootViewController;

            if (rootController.PresentedViewController == null)
                return rootController;

            if (rootController.PresentedViewController is UINavigationController)
            {
                return ((UINavigationController)rootController.PresentedViewController).VisibleViewController;
            }

            if (rootController.PresentedViewController is UITabBarController)
            {
                return ((UITabBarController)rootController.PresentedViewController).SelectedViewController;
            }

            return rootController.PresentedViewController;
        }
```

**Additional context**
Should be easily reproducible by putting on a page and calling it with PushModalAsync()

 I didn't do a pull request because I had to manually put the controls into my project since it is using a PCL and not NetStandard2.0.

**Comment by enisn** [comment]
@mxstudios 
Thank you for your contribution. I'm fixing it immediately.

**Comment by enisn** [comment]
It'll be included on v.2.3.5+
