### ISSUE TITLE
Dropdown cause crash in android5.0

### ISSUE THREAD

**Issue by devinZhou102** [enisn/Xamarin.Forms.InputKit#34]
**Dropdown cause crash in android5.0**
In Android5.0 Dropdown cause crash, the exeption is   

> Java.Lang.NoSuchMethodError: no non-static method "Landroid/widget/PopupMenu;.setGravity(I)V"

**Comment by devinZhou102** [comment]
1. use MonoAndroid81
2.  two ways to solve this issue
    a. if use Android.Widget.PopupMenu andandroid version lower than 6.0, do not set Gravity
    `if (OS.Build.VERSION.SdkInt >= OS.BuildVersionCodes.M)
     {
         popup.Gravity = GravityFlags.Right;
     }`
     b. use Android.Support.V7.Widget.PopupMenu

**Comment by enisn** [comment]
I can not build multi-targeting proje after Visual Studio last update, I'll update pluging when I solve that problem too.

**Comment by devinZhou102** [comment]
@enisn I meet another question after change  Android.Widget.PopupMenu to  Android.Support.V7.Widget.PopupMenu,

> Android.Views.InflateException: Binary XML file line #14: Failed to resolve attribute at index 6: TypedValue{t=0x3/d=0x31e "res/drawable/ic_menu_moreoverflow_material.xml" a=1 r=0x10803d6}

It's work well while using Android.Widget.PopupMenu . 
So I try Android.Support.V7.Widget.PopupMenu in Xamarin.Android, it works well too.
I get confused!
do you meet this issue?

**Comment by enisn** [comment]
@devinZhou102  I've tested and got same error. I'm trying Build & Publish right now. I can not release new version because of monodroid and Xamarin.iOS dependencies. When I solved build problem, I'll look again that problem.

**Comment by enisn** [comment]
New version [v.2.3.1](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.1) released. 
You can find changelog from [here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.1).

That problem solved at v.2.3.1 and above.

You can find it [here ](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.1)on Nuget

**Comment by devinZhou102** [comment]
@enisn Hi, that's unlucky, the new version crashes with the exception:

> Unhandled Exception:
Java.Lang.RuntimeException: Failed to resolve attribute at index 6


Now  I don't have any idea to solve it ,but change Android.Support.V7.Widget.PopupMenu to Android.Widget.PopupMenu
