### ISSUE TITLE
Enhancements for RadioButton and CheckBox

### ISSUE THREAD

**Issue by pikausp** [enisn/Xamarin.Forms.InputKit#348]
I'd like to submit a PR that would align the text behaviors for `CheckBox` and `RadioButton` with some enhancements and fixes. These would be the main changes:

- The text wrapping for `CheckBox` doesn't take into account spacing on the `StatefulStackLayout` and hence the text can overflow (fix for this)
-  Add the workaround for text wrapping that is used in `CheckBox` to `RadioButton`
- Remove the maximum number of lines on the `RadioButton` (it doesn't exist on the `CheckBox`) or expose this as a bindable property on both if you deem it necessary
- Align the label configuration of both controls
- Expose a bindable property that would allow you to position the icon vertically. The main use case is when the text gets wrapped so the user can alter the location of the icon. Center is not always desired
- Expose a bindable property that would allow you to position the icon horizontally. The main use case is when you have `Vertical` orientation. Center is not always desired
- Expose a bindable property to propagate `LineBreakMode`
- Expose a bindable property to propagate `FontFamily`

What is your take on this?

**Comment by pikausp** [comment]
@enisn Hi, don't mean to rush you, but do you have a moment to take a look at the proposed changes so I can get started?

**Comment by enisn** [comment]
Yes it seems right. You can take an action,
By the way sorry for my late response, I paused notifications from InputKit a while ago. I'm watching this repo again
