### ISSUE TITLE
Horizontal RadioButton

### ISSUE THREAD

**Issue by rredoh** [enisn/Xamarin.Forms.InputKit#37]
When I try to make RadioButton displayed horizontally, it work like CheckButton..
Small reproduction
RadioButton Broken :
```
<inputKit:RadioButtonGroupView>
  <Grid>
     <inputKit:RadioButton Text="Choice 1" Grid.Column=0/>
     <inputKit:RadioButton Text="Choice 2" Grid.Column=1/>
     <inputKit:RadioButton Text="Choice 3" Grid.Column=2/>
  </Grid>
</inputKit:RadioButtonGroupView>

```

Working normally but stay vertical :
```
<Grid>
  <inputKit:RadioButtonGroupView>
     <inputKit:RadioButton Text="Choice 1" Grid.Column=0/>
     <inputKit:RadioButton Text="Choice 2" Grid.Column=1/>
     <inputKit:RadioButton Text="Choice 3" Grid.Column=2/>
  </inputKit:RadioButtonGroupView>
</Grid>
```

**Comment by enisn** [comment]
I think same with: #15 

You can use SelectionView instead of using grid: 
Theese can help:
- [Add a label to RadioButtonGroupView](https://github.com/enisn/Xamarin.Forms.InputKit/issues/15#issuecomment-405299418)
- [Adding dynamicly RadioButtons](https://github.com/enisn/Xamarin.Forms.InputKit/wiki/Adding-dynamicly-RadioButtons) on WiKi

**Comment by enisn** [comment]
> I think same with: #15
> 
> You can use SelectionView instead of using grid:
> Theese can help:
> 
> * [Add a label to RadioButtonGroupView](https://github.com/enisn/Xamarin.Forms.InputKit/issues/15#issuecomment-405299418)
> * [Adding dynamicly RadioButtons](https://github.com/enisn/Xamarin.Forms.InputKit/wiki/Adding-dynamicly-RadioButtons) on WiKi

@rredoh does it help ?  or I can support to your code.

**Comment by enisn** [comment]
@rredoh I suggest you to use **[SelectionView](https://github.com/enisn/Xamarin.Forms.InputKit/wiki/SelectionView)** but you can try another method.
I'm not sure will it help you but you can try also:

```xml
<inputKit:RadioButtonGroupView Orientation="Horizontal">
     <inputKit:RadioButton Text="Choice 1" Grid.Column=0/>
     <inputKit:RadioButton Text="Choice 2" Grid.Column=1/>
     <inputKit:RadioButton Text="Choice 3" Grid.Column=2/>
</inputKit:RadioButtonGroupView>
```

**Comment by rredoh** [comment]
Works like a charm.. 
Very fast response and very nice kit..:)
Thank you very much for making my life easier :)
