### ISSUE TITLE
Version 2.3.1 throwing exception: Android.Views.InflateException

### ISSUE THREAD

**Issue by LeoJHarris** [enisn/Xamarin.Forms.InputKit#39]
New version 2.3.1 is throwing exception:

Android.Views.InflateException: Binary XML file line #14: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f0100a0 a=-1}

Having rolled back to version 2.3.0 issue went away.

Latest Xamarin.Forms 3.2.0.839982.

Target android Version 9.0 (28)
Min Android Version 5.0 (21)
Compile using Android Version 9.0 (28)

Device API is 7.1.1

**Comment by devinZhou102** [comment]
fixed in [pull38](https://github.com/enisn/Xamarin.Forms.InputKit/pull/38)

**Comment by enisn** [comment]
Pull #38  included on new version.
