### ISSUE TITLE
PlaceholderTextColor - Dropdown

### ISSUE THREAD

**Issue by LeoJHarris** [enisn/Xamarin.Forms.InputKit#40]
Drop-down component to add ability to change/customize placeholder text color beyond the light gray color it currently defaults with.

**Comment by enisn** [comment]
@LeoJHarris  Finally **PlaceholderColor** added to **dropdown** on new version [v.2.3.3](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.3)
