### ISSUE TITLE
Color property not being honored for dropdown option. 

### ISSUE THREAD

**Issue by LeoJHarris** [enisn/Xamarin.Forms.InputKit#41]
Color property not being honored for dropdown option. 

When setting the color to something like Green, I keep getting the red color it defaults with. Doesn't seem to honor the Color property.

`<input:Dropdown
                Title="Chosse an option below:"
                AnnotationColor="Accent"
                BorderColor="Black"
                IconImage="icon.png"
                IsEditable="False"
                IsRequired="True"
                ItemsSource="{Binding MyList}"
                Placeholder="Choose one"
                SelectedItem="{Binding SelectedItem}"
                TitleColor="Black"
                ValidationMessage="This field is required"
                Color="Green" />`

This is the xaml and should override the red color being displayed. Ignore the actual image I am using the sample and set the IconImage as icon.png for simplicity but would still expect image color to change to black.

![device-2018-09-28-114950](https://user-images.githubusercontent.com/5468757/46180535-12af2d80-c315-11e8-984d-131a67bdd367.png)

**Comment by enisn** [comment]
@LeoJHarris 
You need to use a PNG image with Alpha channels. Color will fills all pixels except alpha channels. You can use [Material Icons](https://material.io/tools/icons/?style=baseline) for better result.


You need use icons like that:
<img src="https://github.com/google/material-design-icons/blob/master/action/drawable-hdpi/ic_account_balance_black_48dp.png?raw=true" />

and if you set Color white of dropdown, it'll be like:

<img src="https://github.com/google/material-design-icons/blob/master/action/drawable-hdpi/ic_account_balance_white_48dp.png?raw=true" />

**Comment by enisn** [comment]
I understand the real bug. Color doesn't affect anytime.
I'm working on it.
![Image with accent color](https://scontent.fada1-9.fna.fbcdn.net/v/t1.15752-9/43721090_340307676718274_8590238207533121536_n.jpg?_nc_cat=100&oh=17ca19f5b4ccb7960a2094ad68c9088f&oe=5C43A81E)

**Comment by enisn** [comment]
It's solved now. It'll be available on v.2.3.4 and newer versions

![Xamarin Forms Dropdown with Color](https://scontent.fada1-9.fna.fbcdn.net/v/t1.15752-9/43581312_514192832382040_1100938690789638144_n.jpg?_nc_cat=102&oh=bcf242c544bb02d19f8e948e7e777e00&oe=5C17B28C)
