### ISSUE TITLE
Radio Button Checked Value bahaves differently across the Platforms.

### ISSUE THREAD

**Issue by toyins46** [enisn/Xamarin.Forms.InputKit#42]
Bug: The value of the Radion Button Checked is different for iOS and Android.
When one attempts to Check a Radio Button using MVVM, the value in Android is true
and the value in iOS is false.
E.g
<controls:RadioButton x:Name="RadioButton" 
                                          Color="Black" 
                                          CircleColor="Orange"
                                          HorizontalOptions="EndAndExpand"
                                          IsEnabled="{Binding RadioButtonIsEnabled}" 
                                          Text=""
                                          IsChecked="{Binding RadioButtonChecked, Mode=TwoWay}"
                                          ClickCommand="{Binding TranslateCommand}">

In the View Model: Android RadioButtonChecked is true
and in iOS RadioButtonChecked is false.

I think they need to both return true, when the user checks the Radio Button.

**Comment by enisn** [comment]
Can you try check it from **ReadioButtonGroupView**  via **SelectedItem**.

```xml
               <input:RadioButtonGroupView SelectedIndex="{Binding SelectedRadioButtonIndex}">
                <input:RadioButton Text="Option 1"  />
            </input:RadioButtonGroupView>
```

You can check if **SelectedIndex** is -1 or not if you have 1 Radio Button. 

I started to look what is problem with **IsChecked**. But you can try this method until I'll find the problem.

**Comment by enisn** [comment]
I think this was resolved at [V3 Release](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.0)

if will problem continue again, just re-open this issue.
