### ISSUE TITLE
can't install 2.3.4 to PCL project

### ISSUE THREAD

**Issue by henryyue2010** [enisn/Xamarin.Forms.InputKit#48]
Hi, 
I tried to install the package to my PCL project, but got issue: Could not install package 'Xamarin.Forms.InputKit 2.3.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

It seems the package doesn't support .net framework 4.5. Can the issue be fixed?
Thank you very much.

**Comment by henryyue2010** [comment]
I was able to use the controls manually in https://github.com/enisn/Xamarin.Forms.InputKit/tree/master/InputKit/Shared

**Comment by enisn** [comment]
Last build, targets netstandard2.0; MonoAndroid81; Xamarin.iOS10; and uap10.0.16299;
