### ISSUE TITLE
the button and text in RadioButton are not vertically centered

### ISSUE THREAD

**Issue by henryyue2010** [enisn/Xamarin.Forms.InputKit#49]
I am using the RadioButton in https://github.com/enisn/Xamarin.Forms.InputKit/blob/master/InputKit/Shared/Controls/RadioButton.cs

I found that the button and text are not quite vertically centered. Is it possible to improve that?

**Comment by enisn** [comment]
It just improved on [v.2.3.5 Release](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.5)

You can find new version from Nuget to clicking [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.5).

**Comment by henryyue2010** [comment]
It works now. Thank you very much for the work.
