### ISSUE TITLE
UWP CheckBox needs tap on text to toggle

### ISSUE THREAD

**Issue by NightOwlCoder** [enisn/Xamarin.Forms.InputKit#50]
Using nuget package Xamarin.Forms.InputKit Version 2.3.4, you need to tap on the text of a combobox to make it togle.
tapping on the box does nothing.
works fine on iOS/Droid.

**Comment by enisn** [comment]
@NightOwlCoder  
UWP support is experimental now.  
I'll work on it and v3 will support UWP fully too.

**Comment by jlhernandez1388** [comment]
@enisn When will v3 come out? Also apart of the toggle problem I have a problem of multiple events firing with checkbox's clicked on list views. This problem is only on UWP.

**Comment by stewartsims** [comment]
Also curious on when UWP support will be added. @enisn Do you have an idea of would be needed to add this support? Could it be something another collaborator could help with?

**Comment by enisn** [comment]
Closing this issue since v4.0 comes with Windows support.
