### ISSUE TITLE
Filled Checkbox when selected?

### ISSUE THREAD

**Issue by NightOwlCoder** [enisn/Xamarin.Forms.InputKit#51]
Hey there, thank you for this great library.
I see on the main page that you have a filled checkbox?

![checkbox](https://camo.githubusercontent.com/7aa6b380224413dc27770e8305d3d60856f17e1f/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f424c6a655a5574494442753764474d5270562f67697068792e676966)

How do I achieve the same effect?
I want this filled box when selected.

**Comment by enisn** [comment]
Just set Type="Material" of Checkbox.

**Comment by NightOwlCoder** [comment]
Just to complement information above, on iOS box is perfect. 
Still not test on Droid.

**Comment by enisn** [comment]
UWP support is experimental. Fully UWP support will be added on v.3.x
