### ISSUE TITLE
Option to change the shape of Check in Checkbox?

### ISSUE THREAD

**Issue by henryyue2010** [enisn/Xamarin.Forms.InputKit#56]
## My Question Here ?

Is there a way to change the shape of check in checkbox like this?

![checkbox](https://user-images.githubusercontent.com/16337520/48529849-e322a780-e8f9-11e8-8734-35229881e927.png)

**Comment by enisn** [comment]
In IOS, it's displaying System Check Shape.

 But Android it's using Check Ascii character  `✓ ` (_2713_).
✔ _2714_ ascii is displaying as Emoji, That's why it uses 2713 ascii code.

But an option can be added for custom image using in checkbox.

**Comment by enisn** [comment]
It's now available at v.3.0.0

For more information [visit Release Notes].(https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.0-pre5)

**Comment by enisn** [comment]
You can just try following codes to customize your own CheckBox:

```xml
            <input:CheckBox Text="Something" Type="Custom" CustomIcon="ic_account_balance_black" Color="Blue"/>
```
