### ISSUE TITLE
Text not aligning well vertically with the Radio Button in the SelectionView Control.

### ISSUE THREAD

**Issue by toyins46** [enisn/Xamarin.Forms.InputKit#57]
**Describe the bug**
Once the list is bound to the SelectionView via the ItemSource in MVVM, the list shows up on iOS and Android. However, the text does not align well vertically with the Radio button to the left of the text in the list.

**To Reproduce**
<input:SelectionView ColumnNumber="1"
                     ColumnSpacing="0" 
                     RowSpacing="0" 
                     VerticalOptions="Center"
                     Color="White"  
                     SelectionType="RadioButton"
                     ItemsSource="{Binding AnswerList}"
                     SelectedIndex="{Binding SelectedQuizAnswerIndex}"
                     ItemDisplayBinding="{Binding AnswerToDisplay}"
                     SelectedItem="{Binding SelectedAnswerItem}"/>

**Comment by enisn** [comment]
I really couldn't get that issue. 

Can you share a screenshot about it?

**Comment by enisn** [comment]
That it resolved at v.3.0.0-pre5.
You can [visit here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.0-pre5) to release notes.
