### ISSUE TITLE
SelectionIndex no longer working in SelectionView.

### ISSUE THREAD

**Issue by toyins46** [enisn/Xamarin.Forms.InputKit#58]
**Describe the bug**
I set the SelectionIndex = -1 in the SelectionView control to deselect all Radio BUttons, so that no Radio Button on the list is selected. However, the first Radio Button is selected by default even though the SelectionIndex is set to -1. I tried hardcoding the value just to test but it still defaults to the first one.
I'm using MVVM by the way.

**To Reproduce**
     <input:SelectionView ColumnNumber="1"
                                                         ColumnSpacing="0" 
                                                         RowSpacing="0" 
                                                         VerticalOptions="Center"
                                                         Color="White"  
                                                         SelectionType="RadioButton"
                                                         ItemsSource="{Binding AnswerList}"
                                                         SelectedIndex="{Binding SelectedQuizAnswerIndex}"
                                                         ItemDisplayBinding="{Binding AnswerToDisplay}"
                                                         SelectedItem="{Binding SelectedAnswerItem}">

and

<input:SelectionView ColumnNumber="1"
                                                         ColumnSpacing="0" 
                                                         RowSpacing="0" 
                                                         VerticalOptions="Center"
                                                         Color="White"  
                                                         SelectionType="RadioButton"
                                                         ItemsSource="{Binding AnswerList}"
                                                         SelectedIndex="-1"
                                                         ItemDisplayBinding="{Binding AnswerToDisplay}"
                                                         SelectedItem="{Binding SelectedAnswerItem}">

**Expected behavior**
No selection.

**Comment by enisn** [comment]
That will be solved next NuGet release.

**Comment by enisn** [comment]
Fixed SelectedIndex at v2.3.6

<hr />

You can visit new version(2.3.6) from [here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/2.3.6). 
or
You can use NuGet package from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.6).
