### ISSUE TITLE
SelectionView with SelectionType.CheckBox doesn't work

### ISSUE THREAD

**Issue by Juansero29** [enisn/Xamarin.Forms.InputKit#59]
**Describe the bug**
The SelectionView with SelectionType.CheckBox doesn't work. No items can't be checked from the grid of items.

**To Reproduce**
1. Declare a SelctionView in XAML
`        <controls1:SelectionView x:Name="SelectionView"/>`
2. Fill it with items and change its selection type on code-behind

```
SelectionView.ItemsSource = new[]
    {
        "Option 1","Option 2","Option 3","Option 4","Option 5","Option 6","Option 7","Option 8"
    };

SelectionView.SelectionType = Plugin.InputKit.Shared.Controls.SelectionType.CheckBox;
```

3. Build & Deploy the project
4. Try to check the items (the items don't check themselves, only the first item is checked and after a tap on the control it unchecks itself, then nothing happens)

**Expected behavior**
The items should check and uncheck each time we tap on them.

**Additional context**
Using the latest stable Xamarin.Forms v3.4.0.1008975 and Plugin.CurrentActivity v2.1.0.4 on the Android project

**Comment by Juansero29** [comment]
I forgot to specify that I tested only on iOS and Android. The control doesn't work in none of them

**Comment by enisn** [comment]
Thanks for the feedback. I'm trying to find when the problem started, 

You can try earlier versions until I find the solution

**Comment by henryyue2010** [comment]
@enisn  I met the same issue. Does @Juansero29 's solution work?

**Comment by TommyLiu1** [comment]
@enisn I also met the same issue in 2.3.5. Is any workaround now?

**Comment by enisn** [comment]
There is a HotFix for this problem at v2.3.6.1

<hr />

You can visit new version(2.3.6.1) from [here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/2.3.6.1). 
or
You can use NuGet package from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.6.1).
