### ISSUE TITLE
Dropdown Text color not working

### ISSUE THREAD

**Issue by BogaDev** [enisn/Xamarin.Forms.InputKit#60]
Hi! Very like your plugin, but there is one problem. 
When I set TextColor to my Dropdown it just doesn't influence on it. 
No matter where I try to do it. Neither  XAML nor CS file.
I tried to set my color to PlaceHolderColor, but there is nothing changed anyway.
I tried on Android, don't know about IOS.

**Comment by devanshukanik** [comment]
Same here I also tried setting the color Globally that too not working.

**Comment by enisn** [comment]
Thanks for your feedback 👍 
This is added to planned fixes list on new version.

**Comment by enisn** [comment]
This problem solved at v2.3.6.

Also you can visit [Dropdown Coloring](https://github.com/enisn/Xamarin.Forms.InputKit/wiki/Dropdown-Coloring) Guide

You can visit new version(2.3.6) from [here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/2.3.6). 
or
You can use NuGet package from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.6).
