### ISSUE TITLE
how to set text size in SelectionView with SelectionType="RadioButton"

### ISSUE THREAD

**Issue by henryyue2010** [enisn/Xamarin.Forms.InputKit#63]
## My Question Here ?
I created a group of radios using the example in wiki 

```xml
   <input:SelectionView ColumnNumber="1" SelectionType="RadioButton" ItemsSource="{Binding MyList}" SelectedItem="{Binding SelectedItem}"  />
```

but the Text Size in RadioButton is not good. How to change the Text Size in SelectionView?

Thank you very much.
Henry

**Comment by enisn** [comment]
Try to add following GlobalSetting in **App.cs**:

```csharp
//Sets default fontsize for all RadioButtons
RadioButton.GlobalSetting.FontSize = 18;

//or with all namespace:
Plugin.InputKit.Shared.Controls.RadioButton.GlobalSetting.FontSize = 18;
```

> **WARNING:** This setting will applied in your entire app.

**Comment by henryyue2010** [comment]
@enisn That's it. Thank you very much.
