### ISSUE TITLE
checkbox taking up too much space, not fitting inside box shape

### ISSUE THREAD

**Issue by shahbaaz90** [enisn/Xamarin.Forms.InputKit#64]
**Describe the bug**
the checkbox control height goes beyond the scope defined in heightrequest or BoxSizeRequest.

**To Reproduce**
Create a checkbox control inside a grid
                    <inputkit:CheckBox
                        BackgroundColor="Blue"
                        Grid.Row="1"
                        Grid.Column="0"
                        HorizontalOptions="Start"
                        VerticalOptions="Center"
                        BoxSizeRequest="18"
                        Margin="0,0,20,0"
                        Type="Check"
                        Color="{StaticResource AccentColor}"
                        BorderColor="{StaticResource LightFontColor}"
                        BoxBackgroundColor="{StaticResource LightGrayish}" />

**Expected behavior**
box should take a square shape, which it does. but the space occupied in the background is not a square shape, but rectangular.
<img width="296" alt="screenshot 2019-01-14 at 22 54 35" src="https://user-images.githubusercontent.com/9108018/51130693-6b1c2380-184f-11e9-93c9-f80f59628f3a.png">

**Comment by enisn** [comment]
Can you try to set **Padding** and **Margin** as Zero for checkbox
```xml
<inputkit:CheckBox Margin="0" Padding="0"/>
```

Did it help ?

**Comment by shahbaaz90** [comment]
> @shahbaaz90
> Can you try to set **Padding** and **Margin** as Zero for checkbox
> 
> ```
> <inputkit:CheckBox Margin="0" Padding="0"/>
> ```
> 
> Did it help ?

@enisn yep, setting padding to zero solved it. thanks ! :)
