### ISSUE TITLE
RadioButton inside RadioButtonGroup is not initially checked according to binding.

### ISSUE THREAD

**Issue by vchelaru** [enisn/Xamarin.Forms.InputKit#67]
**Describe the bug**
Radio Buttons should be checked according to the bound Value on the RadioButtonGroup, but they are not.

**To Reproduce**
1. Create a new RadioButtonGroupView
1. Call NewRadioButtonGroup.SetBinding(RadioButtonGroupView.SelectedItemProperty, "PropertyName") to bind the group to a value in a view model
1. Create a property in the view model of Enum type with values like "First", "Second", "Third"
1. Set the default value in your view model to "First" (should happen anyway if it's a non-nullable enum
1. Add multiple RadioButton instances to your RadioButtonGroupView, making sure one of them has `radioButton.Value = MyEnum.First;`
1. Make sure your page has its BindingContext set to an instance of the view model.
1. Run the project

**Expected behavior**
The expected behavior is when the BindingContext on the Group changes (when the view model is assigned), the group should inspect the current SelectedItem property on the view model and if any contained RadioButtons have that as their Value, the RadioButton should be checked.

Instead, no buttons are checked whatsoever.

Workaround - can get around this by binding to bools that mirror the selected value.

Additional note - I have verified that my binding works correctly because if I check the RadioButtons by tapping on them at runtime, the setter on my view model gets set.

**Screenshots**

![image](https://user-images.githubusercontent.com/729631/52084598-a6ad3200-255f-11e9-906d-2fb75a85efc4.png)

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G6
 - OS: Android 8.0

**Comment by vchelaru** [comment]
I have a simplified scenario which requires no view model nor binding:

```
        enum MyEnum
        {
            First,
            Second
        }

        void SomeSetupFunction()
        {
            var group = new RadioButtonGroupView();

            var firstButton = new RadioButton("First"
            firstButton.Value = MyEnum.First;
            group.Children.Add(firstButton);

            var secondButton = new RadioButton("Secon
            secondButton.Value = MyEnum.Second;
            group.Children.Add(secondButton);

            // Both radio buttons are part of the group so this should set the values
            group.SelectedItem = MyEnum.First;

            // Whatever is needed to add the control to the page

```

**Comment by enisn** [comment]
> I have a simplified scenario which requires no view model nor binding:
> 
> ```
>         enum MyEnum
>         {
>             First,
>             Second
>         }
> 
>         void SomeSetupFunction()
>         {
>             var group = new RadioButtonGroupView();
> 
>             var firstButton = new RadioButton("First"
>             firstButton.Value = MyEnum.First;
>             group.Children.Add(firstButton);
> 
>             var secondButton = new RadioButton("Secon
>             secondButton.Value = MyEnum.Second;
>             group.Children.Add(secondButton);
> 
>             // Both radio buttons are part of the group so this should set the values
>             group.SelectedItem = MyEnum.First;
> 
>             // Whatever is needed to add the control to the page
> ```

that is better to understand problem.

For now, as I see, '==' comparison is from [here](https://github.com/enisn/Xamarin.Forms.InputKit/blob/8f94bd831d418941a21618c6dcff5cee4aa269e6/InputKit/Shared/Controls/RadioButton.cs#L147) doesn't work for your Enums.

Current code:
```csharp
(item as RadioButton).IsChecked = (item as RadioButton).Value == value;
```

<hr />
The following changes may solve that problem, I'll try and publish a new version as soon as possible

```csharp
(item as RadioButton).IsChecked = (item as RadioButton).Value.Equals(value);
```

**Comment by vchelaru** [comment]
Yea, that makes sense, the == on enum values will return false because it is comparing the boxed values.

Let me know when it's released and I can try updating my code. In the meantime I've coded a work-around.

**Comment by enisn** [comment]
@vchelaru ,

New version is released. Probably your problem was solved too. Can you check in new version and write result ?

<hr />

You can visit new version(2.3.6) from [here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/2.3.6). 
or
You can use NuGet package from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.6).

**Comment by vchelaru** [comment]
I just tried it, everything works great!
