### ISSUE TITLE
SelectionView: Selecting multiple items in SelectionType.Button configuration

### ISSUE THREAD

**Issue by Cocotus** [enisn/Xamarin.Forms.InputKit#68]
First thanks for this project, I love the layout of the selectionview in button configuration and it works fine if radio button behaviour is asked (only one item can be selected at one time). But what if I want to allow selecting multiple items? I noticed some properties in the code like SelectedItems and SelectedIndexes so it seems there is something implemented here,  but I cant get it to work in Buttonconfig. Am I missing something?

**Comment by enisn** [comment]
Thanks for specifying this requirement.

In 2.3.6 version **SelectionView** supports multiple selection for Type of **CheckBox** only.

<hr />

Multiple Selection will be added to Type of Button at next version

**Comment by Cocotus** [comment]
That sounds awesome thanks!  :+1:  Maybe it's a good idea to offer a new property like "AllowMultipleSelections"  for that, so we can decide which behaviour we want?

**Comment by enisn** [comment]
https://github.com/enisn/Xamarin.Forms.InputKit/blob/872e0f90bd55643a0c2e38d4767df54d5156acb3/InputKit/Shared/Controls/SelectionView.cs#L261-L274

from here there is a primitive solution to decide allows multiple selection or not :)
Adding a new Enum value with even number will solve problem much more quicker.
https://github.com/enisn/Xamarin.Forms.InputKit/blob/872e0f90bd55643a0c2e38d4767df54d5156acb3/InputKit/Shared/Controls/SelectionView.cs#L365-L373

**Comment by enisn** [comment]
That problem solved.

You may use **MultipleButton** Type of SelectionView to do this like following code:

```xml
            <input:SelectionView ColumnNumber="2" RowSpacing="1" ColumnSpacing="1" SelectionType="MultipleButton" ItemDisplayBinding="{Binding Id}" ItemsSource="{Binding MyList}" />

```

<hr /> 

You can find new version v.2.3.7
Release from [here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.7)
NuGet from [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.7)

**Comment by AirCallInc** [comment]
@enisn  2.3.7 cannot work in iOS, please help to check.The following is error message:
Error MT2101: Can't resolve the reference 'System.String[] System.String::Split(System.Char,System.StringSplitOptions)', referenced from the method 'System.Boolean Plugin.InputKit.Shared.Controls.AdvancedEntry::get_IsAnnotated()' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. (MT2101)

**Comment by enisn** [comment]
> @enisn 2.3.7 cannot work in iOS, please help to check.The following is error message:
> Error MT2101: Can't resolve the reference 'System.String[] System.String::Split(System.Char,System.StringSplitOptions)', referenced from the method 'System.Boolean Plugin.InputKit.Shared.Controls.AdvancedEntry::get_IsAnnotated()' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. (MT2101)

If older version doesn't throw that Error, please try Delete **/obj** folder from your project root and generate again via building project.

If that happens at earlier versions, I'm moving that problem as new issue.

**Comment by Cocotus** [comment]
Awesome, thanks for quick implementation and release! I'm at home now and going to test this in my project (UWP) later and report back.

**Comment by Cocotus** [comment]
EDIT: Works fine! Thanks again!
