### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by JADSN** [enisn/Xamarin.Forms.InputKit#7]
Can you make a sample of _SelectableRadioButton_, _FormView_, _IconView_ and _AdvancedEntry_ ?

```xaml
        <input:RadioButtonGroupView x:Name="rbgv">
            <input:RadioButton Text="What" Value="What" IsChecked="False"/>
            <input:RadioButton Text="Where" Value="Where" IsChecked="False"/>
            <input:RadioButton Text="When" Value="When" IsChecked="True"/>
            <input:RadioButton Text="Who" Value="Who" IsChecked="False"/>
        </input:RadioButtonGroupView>

        <Label Text="{Binding Source={x:Reference rbgv}, Path=SelectedItem, Mode=TwoWay}" />
```

In code above, the label doesn't change the item or value(using Path=SelectedItem) when check other RadioButton in same group.

**Comment by enisn** [comment]
I think It does not trigger bindable property in source code, I'm working on, 

For the first question, formview is not stable yet, it will help validating inputs easily, 

I'll create wiki as soon as possible

**Comment by enisn** [comment]
I've just updated to v.1.0.9, 
BindableProperty addded to SelectedItem, SelectedItemChanged event and SelectedItemChangedCommand command added to RadioButtonGroupView

**Comment by enisn** [comment]
@JADSN  I have just started generate Wiki content of Package inside Wiki Tab [Wiki Tab](https://github.com/enisn/Xamarin.Forms.InputKit/wiki).

**Comment by josebarrontovar** [comment]
How do I get the value each time I slide the slider?
  Value = "{Binding Path = Status, Mode = TwoWay}" // XAML

  public double Status {get; set; }
         public MainPage ()
{// CODEBH
             var x = this.Status;
}

Greetings.
