### ISSUE TITLE
Slider value position seems to ignore min value.

### ISSUE THREAD

**Issue by vchelaru** [enisn/Xamarin.Forms.InputKit#70]
**Describe the bug**

The position of the slider value label seems to ignore the min value when it is positioned (as if the min value is always 0).

**To Reproduce**
1. Add the following code:
```
            var slider = new AdvancedSlider();
            slider.TextColor = Color.Black;
            slider.MaxValue = 4;
            slider.MinValue = 3;
            slider.StepValue = .1;
            slider.Value = 3.5;
```
2. Run the program
3. Observe that the 3.5 value is not positioned in the center of the slider where the thumb is located. Instead it is to the far-right.

**Expected behavior**
The value label should appear in the middle of the slider because 3.5 is halfway between 3 and 4.

**Screenshots**
![image](https://user-images.githubusercontent.com/729631/52676361-24b9f300-2ee7-11e9-8fa5-6a191b393d7b.png)

**Smartphone (please complete the following information):**
 - Motorolo Moto G6
 - Android 8.0

**Comment by enisn** [comment]
@vchelaru 

https://github.com/enisn/Xamarin.Forms.InputKit/blob/87b3661be8647dd99892d445baa916265b795849/InputKit/Shared/Controls/AdvancedSlider.cs#L57

In that line, decimal numbers modulo operator returns **0,099999...** for `3.8 % 0.1` operation because of Binary Problem with floating numbers like [this](https://0.30000000000000004.com/).

**Comment by enisn** [comment]
@vchelaru 
AdvancedSlider does not get 0 as start value anymore. and step values mod problem is solved at v.2.3.8 and released

<hr /> 

Release notes are [here](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.8)
NuGet Package is [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.8)

**Comment by vchelaru** [comment]
Fantastic work, thank you so much!
