### ISSUE TITLE
Radiobuttons that are not direct children will not trigger updates properly

### ISSUE THREAD

**Issue by Vannevelj** [enisn/Xamarin.Forms.InputKit#73]
**Describe the bug**
I'm unsure how much of this is intended behaviour and how much of it is a bug. In short, I have a list of items (rows), each with some components including a radio button. I want the radio buttons to all be in the same group, hence if one gets checked then the others get unchecked.

Example layout:

```xml
<input:RadioButtonGroupView>
    <StackLayout>
        <StackLayout>
            <input:RadioButton />
            <Label />
        </StackLayout>
        <StackLayout>
            <input:RadioButton />
            <Label />
        </StackLayout>
    </StackLayout>
</input:RadioButtonGroupView>
```

**To Reproduce**
1. Click on a radio button
2. Click on another
3. Notice that both radio buttons are checked

**Expected behavior**
Only the last radio button is checked.

**Smartphone:**
 - Device: Android
 - OS: 8.1
 - Version: Pixel 2 XL, API Level 27

**Additional context**
My guess is it's related to this line of code (and other places) where you restrict yourself to looking at the `GroupView` its children. My guess is this should be looking at all descendants instead so it's possible to nest the radio buttons a few levels lower.

https://github.com/enisn/Xamarin.Forms.InputKit/blob/e70154b785d814b06ce93fa26a18a3e22b149d2d/InputKit/Shared/Controls/RadioButton.cs#L67-L73

**Comment by enisn** [comment]
Yeah, That's great point. 
I'll solve that bug

**Comment by enisn** [comment]
Until solution will be released you can use [SelectionView ](https://github.com/enisn/Xamarin.Forms.InputKit/wiki/SelectionView)to make columns for RadioButtons by setting **Type** as RadioButton and **ColumnNumber** as how much you want.

```xml
<SelectionView ItemsSource="{Binding OptionsList}" Type="RadioButton" ColumnNumber="3" />
```

You can find some instructions to set-up SelectionView:
- [Adding dynamicly RadioButtons](https://github.com/enisn/Xamarin.Forms.InputKit/wiki/Adding-dynamicly-RadioButtons)

**Comment by enisn** [comment]
@Vannevelj 
[v3.0.4](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.4) has been released just now. Solution of this problem is included that version. 

* * *
<a href="https://www.nuget.org/packages/Xamarin.Forms.InputKit/"><img src="https://img.shields.io/badge/Nuget-3.0.4-blue.svg" /></a>
