### ISSUE TITLE
CheckChanged Event is not firing on iPhone 5s

### ISSUE THREAD

**Issue by delaney31** [enisn/Xamarin.Forms.InputKit#74]
**Describe the bug**
The checkbox CheckChanged event is not firing on the iPhone 5s. It seems to work on other iOS and Android devices.

**To Reproduce**
 checkBox.CheckChanged += CheckBox_CheckChanged;

 void CheckBox_CheckChanged(object sender, EventArgs e)
        {
            CheckUserAcceptance();
        }
**Expected behavior**
I expect the CheckChanged event to be called when box is checked or unchecked

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by enisn** [comment]
Can you check again at newer versions if same problem continues ?

This is last stable pre-release: [v.3.0.0-pre6](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.0-pre6)

**Comment by delaney31** [comment]
Sorry this was not a bug in your component. It was in my code.
