### ISSUE TITLE
Type input:CheckBox not found in xmlns clr-namespace:Plugin.InputKit.Shared.Controls;assembly=Plugin.InputKit on iOS

### ISSUE THREAD

**Issue by SandipAhluwalia** [enisn/Xamarin.Forms.InputKit#75]
Getting strange run-time exceptions on iOS as follows:

Xamarin.Forms.Xaml.XamlParseException: Position 98:34. Type input:CheckBox not found in xmlns clr-namespace:Plugin.InputKit.Shared.Controls;assembly=Plugin.InputKit

Xaml code below in shared .Net 2.0 library works fine when running on Android:

`xmlns:input="clr-namespace:Plugin.InputKit.Shared.Controls;assembly=Plugin.InputKit"`

`<DataTemplate>
     <ViewCell>
         <Grid Margin="0,0,0,12">
             <input:CheckBox Text="{Binding Name}"
                                         Type="Check"
                                         IsChecked="{Binding IsChecked}"
                                         BoxBackgroundColor="{StaticResource bgCheckBoxColor}"
                                         Color="{StaticResource fgLabelColor}"
                                         TextColor="{StaticResource fgLabelColor}"/>
        </Grid>
    </ViewCell>
</DataTemplate>`

Nuget Xamarin.Forms.InputKit package installed across all projects in solution including on the Xamarin.iOS project.

My suspicion is that the type might be getting linked out by the compiler?

**Expected behavior**
No run-time exception.

**Smartphone:**
 - Device: iPhone6
 - OS:  iOS 12.1.3

**Additional context**
Xamarin.Forms.InputKit v2.3.8 and Xamarin.Forms 3.3.0.912540
Xamarin.iOS - 12.2.1.12

**Comment by SandipAhluwalia** [comment]
Unfortunately the claim that 

> No more Init(); methods for your each platform !

in https://github.com/enisn/Xamarin.Forms.InputKit/wiki/Getting-Started seems to be untrue for at least iOS as I resolved the above issue by adding the following line of code in the `FinishedLaunching` override to stop the compiler linking out the library:

`double fontSize = CheckBox.GlobalSetting.FontSize;`

**Comment by enisn** [comment]
I've just created a new Project, added package to each platform, and just called CheckBox from XAML. It worked. 

Can you try delete your **/obj** folder before start.

**Comment by enisn** [comment]
> Unfortunately the claim that
> 
> > No more Init(); methods for your each platform !
> 
> in https://github.com/enisn/Xamarin.Forms.InputKit/wiki/Getting-Started seems to be untrue for at least iOS as I resolved the above issue by adding the following line of code in the `FinishedLaunching` override to stop the compiler linking out the library:
> 
> `double fontSize = CheckBox.GlobalSetting.FontSize;`

Also this NuGet package built from Multi-Targeting Library. You don't need trigger for each platform.

**Comment by enisn** [comment]
@SandipAhluwalia 
You are Right. 
I've just tried Xamarin Forms 3.2.x project. 
Linker doesn't get ios library.  XF 3.4x.x+ versions works fine but lower versions you'll need Init like that until ı've update and add Init method:

> Unfortunately the claim that
> 
> > No more Init(); methods for your each platform !
> 
> in https://github.com/enisn/Xamarin.Forms.InputKit/wiki/Getting-Started seems to be untrue for at least iOS as I resolved the above issue by adding the following line of code in the `FinishedLaunching` override to stop the compiler linking out the library:
> 
> `double fontSize = CheckBox.GlobalSetting.FontSize;`

**Comment by enisn** [comment]
@SandipAhluwalia 
Does problem continues at [v3.0.0](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.0) with new **Init()** methods. _(after following [new set-up](https://github.com/enisn/Xamarin.Forms.InputKit/wiki/Getting-Started))_

* * *


<a href="https://www.nuget.org/packages/Xamarin.Forms.InputKit/"><img src="https://img.shields.io/badge/Nuget-3.0.0-blue.svg" /></a>
