### ISSUE TITLE
Change Border Color and remove Border Corner from SelectionView

### ISSUE THREAD

**Issue by sadhac** [enisn/Xamarin.Forms.InputKit#8]
Hi

Is there a way to remove the border Corner, have a rectangle box for Selection View.
I also want to set the text alignment to Left justification and set the default border color to gray. If the user selects one of the views the color should change to another color.
Please advise.

Thank You

**Comment by enisn** [comment]
I'll add that properties soon, SelectionView uses default buttons, and background color is Device's Accent Color. 

Color Options and border option will be added.

I'm working on it

**Comment by enisn** [comment]
I've added the features to package, but unfortunately I have some troubleshoots with packaging for nuget.

**Comment by sadhac** [comment]
Thanks Enisn
