### ISSUE TITLE
TextSize on AdvancedEntry

### ISSUE THREAD

**Issue by LeoJHarris** [enisn/Xamarin.Forms.InputKit#85]
Hi @enisn regarding AdvancedEntry is there a TextSize property on it? If not can we add one possibly? Thanks

**Comment by enisn** [comment]
@LeoJHarris 
It's included V3.0.0 pre-release
<hr />
<a href="https://www.nuget.org/packages/Xamarin.Forms.InputKit/3.0.0-pre7"><img src="https://img.shields.io/badge/Nuget-3.0.0_pre7-blue.svg" /></a>
