### ISSUE TITLE
Added IsPassword Property to AdvancedEntry control

### ISSUE THREAD

**Issue by muhammetsahin** [enisn/Xamarin.Forms.InputKit#91]
I cant find isPassword property in AdvancedEntry control.

Maybe you should add this.

`
    //------------------------------------------------------------------------
    /// <summary>
    /// IsPassword this control
    /// </summary>
    public bool IsPassword
    {
      get => _isPassword; set
      {
        _isPassword = value;
        txtInput.IsPassword = value;
      }
    }
`

Thanks.

**Comment by enisn** [comment]
Included in v3.0.1

<a href="https://www.nuget.org/packages/Xamarin.Forms.InputKit/"><img src="https://img.shields.io/badge/Nuget-3.0.1-blue.svg" /></a>
