### ISSUE TITLE
Wrong variable name at the getting started page in the wiki

### ISSUE THREAD

**Issue by hhuseyinpay** [enisn/Xamarin.Forms.InputKit#93]
In the Android section written this:
`Plugin.InputKit.Platforms.Droid.Config.Init(this,savedInstance); `
It should be:
`Plugin.InputKit.Platforms.Droid.Config.Init(this,savedInstanceState);`

**Comment by enisn** [comment]
Yeah, Right. 
It's name is `savedInstanceState` at newer versions of Xamarin Forms. 
Thanks for your contributing. I'm updating now. 👍

**Comment by enisn** [comment]
It just resolved.
