### ISSUE TITLE
Extending the Entry of Advance 

### ISSUE THREAD

**Issue by ronakshethia** [enisn/Xamarin.Forms.InputKit#97]
how can i get a bordered entry as my application is using bordered entry and so i tried extending the AdvanceEntry and tried putting border using custom render but i could not achieve 

this is what i am trying to make my entry look like 
![image](https://user-images.githubusercontent.com/35444818/54663032-fe9afa80-4b05-11e9-85d9-3b75bc775b91.png)

what i am getting right now is this 
![image](https://user-images.githubusercontent.com/35444818/54663625-e7f5a300-4b07-11e9-8c8e-88010ae47c8f.png)

also the entry is leave so much space in left and side how can remove that space ?

**Comment by enisn** [comment]
It's using FrameRenderer instead of EntryRenderer. That's why it applies shadow with border color. I'll add support for border color as soon as possible

**Comment by ronakshethia** [comment]
thanx that would work for me at the moment

**Comment by ronakshethia** [comment]
what could i do to remove that extra space ?

**Comment by enisn** [comment]
That space for Icon placement, 
I'll remove that space when icon isn't set in new version 👍

**Comment by enisn** [comment]
@ronakshethia 
Can you try updating [v3.0.4-pre1](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.3.0.4-pre1). This solution is included that pre-release.
 Just set BorderColor _Your Color_ and set BackgroundColor as `Transparent`

**Comment by enisn** [comment]
@ronakshethia 

After v3.0.4-pre1 and above;

You can try something like that:
```xml
<Grid Margin="25">
	<input:AdvancedEntry Grid.Column="0" Title="Height" BorderColor="Black" BackgroundColor="Transparent" CornerRadius="10" />
	<input:AdvancedEntry Grid.Column="1" Title="Width" BorderColor="Black" BackgroundColor="Transparent" CornerRadius="10" />
</Grid>
```

and output:

![image](https://user-images.githubusercontent.com/23705418/54936540-ba5b9000-4f33-11e9-9992-fc851cc5b306.png)

**Comment by get-flat** [comment]
@enisn could you please verified this fix is present in InputKit.Maui version 4.2.0.
On android (simulator) if ImageSource is not set, the empty space reserved for the icon is still displayed.
